export interface QuestionData {
    q: string; op: string[]; ans: number; diff: string; r: string; w: string;
}
export interface LevelData { name: string; questions: QuestionData[]; }
export interface ChapterData { name: string; order: number; levels: LevelData[]; youtubeLink?: string; }

function makeLevels(topics: Record<string, QuestionData[]>): LevelData[] {
    return ['Diagnostic', 'Beginner', 'Intermediate', 'Advance', 'Challenge'].map(n => ({ name: n, questions: topics[n] }));
}

// ========== CHAPTER 1: Rational and Irrational Numbers ==========
const ch1: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Which represents a non-terminating but recurring rational number?', op: ['1/8', '2/5', '1/3', '0.25'], ans: 3, diff: 'MEDIUM', r: 'Correct! 1/3 = 0.333...', w: '1/3 is recurring.' },
        { q: 'Identify the irrational number between √2 and √5:', op: ['2', '1.5', '√3', '2.25'], ans: 3, diff: 'MEDIUM', r: 'Good identification!', w: '√3 is between 1.41 and 2.23.' },
        { q: 'The additive inverse of −5/4 is:', op: ['4/5', '1.25', '−1.25', '0.8'], ans: 2, diff: 'EASY', r: 'Correct!', w: 'Inverse of −1.25 is +1.25.' },
        { q: 'Solve: (2/3 + 1/4) × 12', op: ['10', '11', '12', '9'], ans: 2, diff: 'HARD', r: 'Great mental math!', w: '8+3 = 11.' },
        { q: 'Which is greater: −2/3 or −3/4?', op: ['−2/3', '−3/4', 'Equal', 'Neither'], ans: 1, diff: 'MEDIUM', r: 'Excellent comparison!', w: '−0.66 > −0.75.' },
        { q: 'Value of |−7/3| + 2/3 is:', op: ['−5/3', '3', '1', '9/3'], ans: 2, diff: 'HARD', r: 'Strong absolute value usage.', w: '7/3 + 2/3 = 9/3 = 3.' },
        { q: 'Rational form of 0.666... is:', op: ['6/10', '2/3', '3/2', '6/99'], ans: 2, diff: 'HARD', r: 'Perfect conversion!', w: '0.6... = 2/3.' },
        { q: 'Square root of 2 is:', op: ['Rational', 'Irrational', 'Integer', 'Whole'], ans: 2, diff: 'EASY', r: 'Correct!', w: '√2 is irrational.' },
        { q: 'Find a rational number exactly between 1/4 and 1/2:', op: ['1/3', '3/8', '2/6', '0.3'], ans: 2, diff: 'HARD', r: 'Outstanding calculation!', w: '(0.25+0.5)/2 = 0.375 = 3/8.' },
        { q: 'Is (√2 × √8) rational?', op: ['Yes', 'No', 'Undefined', 'Maybe'], ans: 1, diff: 'HARD', r: 'Amazing! √16 = 4 which is rational.', w: '√16 = 4.' },
    ],
    Beginner: [
        { q: 'Compare (3/5) and (4/7):', op: ['3/5 > 4/7', '3/5 < 4/7', 'Equal', 'None'], ans: 1, diff: 'MEDIUM', r: '21 > 20, correct!', w: 'Cross multiply: 21 vs 20.' },
        { q: 'Value of 0.125 as a fraction:', op: ['1/4', '1/8', '1/6', '1/10'], ans: 2, diff: 'MEDIUM', r: 'Accurate conversion.', w: '0.125 = 1/8.' },
        { q: '−(5 − 11)/2 equals:', op: ['3', '−3', '8', '−8'], ans: 1, diff: 'HARD', r: 'Excellent sign work!', w: '−(−6)/2 = 3.' },
        { q: 'Which is NOT an irrational number?', op: ['π', '√7', '√9', '√11'], ans: 3, diff: 'EASY', r: '√9 = 3 (Rational)!', w: '√9 = 3.' },
        { q: 'Product of two negative rational numbers is always:', op: ['Negative', 'Positive', 'Zero', 'Depends'], ans: 2, diff: 'EASY', r: 'Correct!', w: '(−) × (−) = (+).' },
        { q: 'Express −17/5 as a mixed fraction:', op: ['−3⅖', '−3⅖', '−3⅖', 'None'], ans: 1, diff: 'MEDIUM', r: 'Good!', w: '17/5 = 3 remainder 2.' },
        { q: 'Sum of 1/2, 1/3 and 1/6 is:', op: ['1', '5/6', '11/6', '0.5'], ans: 1, diff: 'HARD', r: '3/6 + 2/6 + 1/6 = 1!', w: 'Sum is 6/6 = 1.' },
        { q: 'Between any two distinct rational numbers, there are ____ rational numbers.', op: ['Finite', 'Zero', 'Infinite', 'One'], ans: 3, diff: 'MEDIUM', r: 'Correct!', w: 'Infinite.' },
        { q: 'Reciprocal of −1 is:', op: ['1', '0', '−1', 'Not defined'], ans: 3, diff: 'MEDIUM', r: 'Perfect!', w: '−1/1 = −1.' },
        { q: 'Solve: 0.5 ÷ 0.05', op: ['1', '10', '100', '0.1'], ans: 2, diff: 'HARD', r: 'Fast division!', w: '50/5 = 10.' },
    ],
    Intermediate: [
        { q: 'Solve for x: x + 3/4 = −1/2', op: ['−1/4', '−5/4', '1/4', '5/4'], ans: 2, diff: 'HARD', r: 'Excellent algebra!', w: '−2/4 − 3/4 = −5/4.' },
        { q: 'Irrational number multiplied by 0 is:', op: ['Irrational', '0', '1', 'Undefined'], ans: 2, diff: 'MEDIUM', r: 'Logical!', w: 'Any real × 0 = 0.' },
        { q: 'Value of (√3)² + (√2)²:', op: ['√5', '5', '13', 'None'], ans: 2, diff: 'MEDIUM', r: 'Accurate!', w: '3 + 2 = 5.' },
        { q: 'Decimal expansion of 7/11 is:', op: ['0.6363...', '0.777...', '0.64', '0.63'], ans: 1, diff: 'HARD', r: 'Great division mastery!', w: '0.63 repeating.' },
        { q: 'Which is rational: √0.4 or √0.04?', op: ['√0.4', '√0.04', 'Both', 'Neither'], ans: 2, diff: 'HARD', r: '√0.04 = 0.2, correct!', w: '√0.04 = 0.2.' },
        { q: 'Simplify: (1/2)⁻¹ + (1/3)⁻¹', op: ['5/6', '5', '6', '1/5'], ans: 2, diff: 'HARD', r: '2 + 3 = 5, amazing!', w: '2 + 3 = 5.' },
        { q: 'A terminating decimal fraction has a denominator with prime factors of:', op: ['2 and 3', '2 and 5', '3 and 5', 'Any prime'], ans: 2, diff: 'HARD', r: 'Advanced theoretical knowledge!', w: 'Only 2 and 5 powers.' },
        { q: 'Is 0.1010010001... rational?', op: ['Yes', 'No', 'Sometimes', 'None'], ans: 2, diff: 'MEDIUM', r: 'Non-recurring, so irrational!', w: 'No repeating pattern.' },
        { q: 'Add: 2√2 + 5√2', op: ['7√4', '10√2', '7√2', '14'], ans: 3, diff: 'MEDIUM', r: 'Good radical sum!', w: 'Just like 2x + 5x.' },
        { q: 'Rationalize the denominator of 1/√2:', op: ['2', '√2', '√2/2', '0.5'], ans: 3, diff: 'HARD', r: 'Perfect method!', w: 'Multiply by √2/√2.' },
    ],
    Advance: [
        { q: 'Express 0.2323... as a fraction:', op: ['23/100', '23/99', '23/90', '2/9'], ans: 2, diff: 'HARD', r: 'Outstanding conversion!', w: 'x = 0.23..., 100x = 23.23..., 99x = 23.' },
        { q: 'Which is the irrational number?', op: ['√225', '√(16/9)', '√0.09', '√24'], ans: 4, diff: 'MEDIUM', r: 'Correct! 24 is not perfect square.', w: '√24 is irrational.' },
        { q: 'Simplify: (3/2) × (4/9) + (1/3)', op: ['1', '2/3', '1/3', '4/3'], ans: 1, diff: 'HARD', r: '12/18 + 6/18 = 1, great!', w: '2/3 + 1/3 = 1.' },
        { q: 'The value of (√5 + √2)(√5 − √2) is:', op: ['7', '3', '√3', '√7'], ans: 2, diff: 'HARD', r: 'Difference of squares: 5−2=3!', w: '5 − 2 = 3.' },
        { q: 'If x = √2 and y = √3, is x+y rational?', op: ['Yes', 'No', 'Only if squared', 'Undefined'], ans: 2, diff: 'MEDIUM', r: 'Sum of irrationals is mostly irrational.', w: 'No.' },
        { q: 'Lowest term of 0.85 is:', op: ['17/20', '85/100', '19/20', '4/5'], ans: 1, diff: 'MEDIUM', r: 'Accurate!', w: '85/100 = 17/20.' },
        { q: 'Which property is represented: a + b = b + a?', op: ['Associative', 'Commutative', 'Distributive', 'Identity'], ans: 2, diff: 'EASY', r: 'Correct!', w: 'Changing order = commutative.' },
        { q: 'Value of π is approximately:', op: ['3.14 (Rational approx)', 'Irrational', 'Both of these', '22/7 (Exact)'], ans: 3, diff: 'HARD', r: 'Deep conceptual understanding!', w: 'π itself is irrational, values are approx.' },
        { q: 'Divide: (5/6) ÷ (−2/3)', op: ['−5/4', '−5/9', '−10/18', '5/4'], ans: 1, diff: 'HARD', r: 'Multiplied by reciprocal, great!', w: '(5/6) * (−3/2) = −15/12 = −5/4.' },
        { q: 'Square of an irrational number is ____ rational.', op: ['Always', 'Never', 'Sometimes', 'Always irrational'], ans: 3, diff: 'HARD', r: 'Yes! √2 sq is 2, but (1+√2) sq is not.', w: 'Sometimes.' },
    ],
    Challenge: [
        { q: 'Value of (√2 + 1)² − (√2 − 1)²:', op: ['2', '4√2', '3', '1'], ans: 2, diff: 'HARD', r: 'Outstanding! Used 4ab formula.', w: '4(√2)(1) = 4√2.' },
        { q: 'Approximate value of √10 is between:', op: ['2-3', '3-4', '4-5', '5-6'], ans: 2, diff: 'MEDIUM', r: 'Correct! 3² < 10 < 4².', w: 'Between 3 and 4.' },
        { q: 'If x = 0.999..., then 10x − x equals:', op: ['9', '8.9', '9.9', '1'], ans: 1, diff: 'HARD', r: 'Proofs that 0.999... = 1!', w: '9.9... − 0.9... = 9.' },
        { q: 'Density property of rational numbers means:', op: ['They are heavy', 'Infinite numbers between two', 'They occupy space', 'None'], ans: 2, diff: 'MEDIUM', r: 'Great!', w: 'Infinitely many exist between points.' },
        { q: 'Simplify: 1 / (2 + √3)', op: ['2 + √3', '2 − √3', '√3 − 2', '1'], ans: 2, diff: 'HARD', r: 'Rationalized perfectly!', w: '4−3=1 in denominator.' },
        { q: 'Which is a purely periodic decimal?', op: ['0.123', '0.1212...', '0.155...', '1.5'], ans: 2, diff: 'HARD', r: 'Correct terminology!', w: 'Decimal starts repeating immediately.' },
        { q: 'The product of a non-zero rational and an irrational is always:', op: ['Rational', 'Irrational', 'Both', 'Fraction'], ans: 2, diff: 'MEDIUM', r: 'Correct!', w: 'Stay irrational.' },
        { q: 'Sum of the first 5 prime numbers:', op: ['25', '28', '18', '11'], ans: 2, diff: 'MEDIUM', r: '2+3+5+7+11 = 28, correct!', w: '28.' },
        { q: 'Which set is closed under division?', op: ['Integers', 'Whole numbers', 'Rational numbers (except 0)', 'Natural numbers'], ans: 3, diff: 'HARD', r: 'Advanced property knowledge!', w: 'Rationals excluding zero.' },
        { q: 'Solve: (√3 + √2) / (√3 − √2) + (√3 − √2) / (√3 + √2)', op: ['10', '5', '2√6', '12'], ans: 1, diff: 'HARD', r: 'Master level algebra! (5+2√6) + (5−2√6) = 10.', w: '10.' },
    ],
};

// ========== CHAPTER 2: Parallel Lines and Transversal ==========
const ch2: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'If two parallel lines are cut by a transversal, the interior angles on the same side are:', op: ['Equal', 'Supplementary', 'Complementary', 'Alternate'], ans: 2, diff: 'EASY', r: 'Correct!', w: 'Co-interior = 180°.' },
        { q: 'A transversal cuts two lines. If corresponding angles are equal, the lines are:', op: ['Perpendicular', 'Parallel', 'Intersecting', 'None'], ans: 2, diff: 'EASY', r: 'Convserse theorem, correct!', w: 'Parallel.' },
        { q: 'Angle 1 and Angle 2 form a linear pair. If Angle 1 = 65°, Angle 2 =:', op: ['65°', '115°', '180°', '25°'], ans: 2, diff: 'MEDIUM', r: 'Accurate!', w: '180 − 65 = 115.' },
        { q: 'Number of pairs of alternate exterior angles formed:', op: ['1', '2', '4', '8'], ans: 2, diff: 'MEDIUM', r: 'Correct!', w: 'Two pairs.' },
        { q: 'If alternate interior angles are (3x) and (x + 30), find x if lines are parallel:', op: ['15', '10', '20', '30'], ans: 1, diff: 'HARD', r: 'Excellent! 3x = x+30 → 2x=30.', w: '15.' },
        { q: 'Vertically opposite angles are always:', op: ['Supplementary', 'Adjacent', 'Equal', 'None'], ans: 3, diff: 'EASY', r: 'Correct!', w: 'Equal.' },
        { q: 'Sum of all angles around a point is:', op: ['180°', '360°', '90°', '270°'], ans: 2, diff: 'EASY', r: 'Good!', w: '360°.' },
        { q: 'If lines l || m and transversal n is perpendicular to l, it is ____ to m.', op: ['Parallel', 'Perpendicular', 'Oblique', 'Skew'], ans: 2, diff: 'MEDIUM', r: 'Logical!', w: 'Perpendicular.' },
        { q: 'Two angles are complementary if their sum is:', op: ['180°', '90°', '360°', '45°'], ans: 2, diff: 'EASY', r: 'Correct!', w: '90°.' },
        { q: 'In an equilateral triangle, each interior angle is:', op: ['90°', '45°', '60°', '180°'], ans: 3, diff: 'MEDIUM', r: 'Good!', w: '60°.' },
    ],
    Beginner: [
        { q: 'Symbol for parallel lines:', op: ['⊥', '||', '=', '≠'], ans: 2, diff: 'EASY', r: 'Good recall.', w: '|| is the symbol for parallel.' },
        { q: 'Perpendicular lines form angle of:', op: ['45°', '90°', '180°', '60°'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Perpendicular = 90°.' },
        { q: 'Corresponding angles are on:', op: ['Same side', 'Opposite side', 'Inside only', 'None'], ans: 1, diff: 'EASY', r: 'Good concept.', w: 'Same side of transversal.' },
        { q: 'Interior angles lie:', op: ['Outside lines', 'Between lines', 'On lines', 'Nowhere'], ans: 2, diff: 'EASY', r: 'Correct understanding.', w: 'Interior = between the lines.' },
        { q: 'Exterior angles lie:', op: ['Between lines', 'Outside lines', 'On lines', 'Nowhere'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Exterior = outside the lines.' },
        { q: 'If ∠1 = 65°, its supplementary angle is:', op: ['65°', '115°', '90°', '25°'], ans: 2, diff: 'MEDIUM', r: 'Good calculation.', w: '180° − 65° = 115°.' },
        { q: 'Alternate exterior angles are:', op: ['Equal', 'Supplementary', 'Complementary', 'None'], ans: 1, diff: 'MEDIUM', r: 'Strong concept.', w: 'Alternate exterior angles are equal.' },
        { q: 'Linear pair angles sum to:', op: ['90°', '180°', '360°', '270°'], ans: 2, diff: 'MEDIUM', r: 'Excellent understanding.', w: 'Linear pair = 180°.' },
        { q: 'If corresponding angle is 130°, alternate interior angle is:', op: ['130°', '50°', '90°', '180°'], ans: 2, diff: 'HARD', r: 'Excellent analytical skills.', w: 'Alternate interior = 180° − 130° = 50°.' },
        { q: 'Two parallel lines have how many transversals possible?', op: ['1', '2', 'Infinite', '0'], ans: 3, diff: 'HARD', r: 'Great reasoning.', w: 'Infinite transversals can cut parallel lines.' },
    ],
    Intermediate: [
        { q: 'Angles on the same side of transversal, one interior one exterior:', op: ['Alternate', 'Corresponding', 'Co-interior', 'None'], ans: 2, diff: 'EASY', r: 'Good identification.', w: 'These are corresponding angles.' },
        { q: 'If two lines are parallel, alternate angles are:', op: ['Unequal', 'Equal', 'Supplementary', 'None'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Alternate angles equal for parallel lines.' },
        { q: 'Transversal makes how many pairs of corresponding angles?', op: ['2', '4', '6', '8'], ans: 2, diff: 'EASY', r: 'Good counting.', w: '4 pairs of corresponding angles.' },
        { q: 'If ∠3 = 55°, vertically opposite angle is:', op: ['55°', '125°', '90°', '35°'], ans: 1, diff: 'EASY', r: 'Excellent recall.', w: 'Vertically opposite = equal.' },
        { q: 'Angles forming a linear pair are:', op: ['Equal', 'Supplementary', 'Complementary', 'Vertical'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Linear pair = supplementary.' },
        { q: 'If co-interior angles are 75° and x, find x:', op: ['75°', '105°', '115°', '85°'], ans: 2, diff: 'MEDIUM', r: 'Good calculation.', w: '180° − 75° = 105°.' },
        { q: 'If alternate angle is 110°, co-interior angle is:', op: ['110°', '70°', '90°', '180°'], ans: 2, diff: 'MEDIUM', r: 'Strong understanding.', w: 'Co-interior = 180° − 110° = 70°.' },
        { q: 'Number of pairs of alternate interior angles:', op: ['1', '2', '4', '8'], ans: 2, diff: 'MEDIUM', r: 'Accurate counting.', w: '2 pairs of alternate interior angles.' },
        { q: 'Lines in the same plane that do not intersect:', op: ['Skew', 'Parallel', 'Perpendicular', 'Concurrent'], ans: 2, diff: 'HARD', r: 'Excellent definition recall.', w: 'Parallel lines are coplanar non-intersecting.' },
        { q: 'If ∠1 = 3x and ∠2 = 2x are co-interior, x =:', op: ['36°', '30°', '45°', '60°'], ans: 1, diff: 'HARD', r: 'Great algebra + geometry.', w: '3x + 2x = 180° → x = 36°.' },
    ],
    Advance: [
        { q: 'If a transversal is perpendicular to one parallel line, it is:', op: ['Parallel to other', 'Perpendicular to other', 'Oblique', 'None'], ans: 2, diff: 'EASY', r: 'Excellent logical thinking.', w: 'Perpendicular to both parallel lines.' },
        { q: 'Corresponding angles are also called:', op: ['F-angles', 'Z-angles', 'X-angles', 'O-angles'], ans: 1, diff: 'EASY', r: 'Good recall.', w: 'Corresponding = F-angles.' },
        { q: 'Alternate angles are also called:', op: ['F-angles', 'Z-angles', 'X-angles', 'O-angles'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Alternate = Z-angles.' },
        { q: 'If both alternate angles are 90°, transversal is:', op: ['Parallel', 'Perpendicular', 'Oblique', 'None'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Both 90° means perpendicular.' },
        { q: 'Sum of all angles at a point:', op: ['180°', '270°', '360°', '90°'], ans: 3, diff: 'EASY', r: 'Correct concept.', w: 'Angles at a point = 360°.' },
        { q: 'If ∠A = 2x+10 and corresponding ∠B = 3x−20, find x:', op: ['30', '25', '20', '35'], ans: 1, diff: 'MEDIUM', r: 'Excellent algebra.', w: '2x+10 = 3x−20 → x = 30.' },
        { q: 'Interior angles on same side are also called:', op: ['Alternate', 'Co-interior', 'Corresponding', 'Vertical'], ans: 2, diff: 'MEDIUM', r: 'Good terminology.', w: 'Same-side interior = co-interior.' },
        { q: 'If one angle is 4x and supplementary angle is 5x, find x:', op: ['20°', '15°', '25°', '10°'], ans: 1, diff: 'MEDIUM', r: 'Strong calculation.', w: '4x + 5x = 180° → x = 20°.' },
        { q: 'Three parallel lines cut by a transversal form how many angles?', op: ['8', '10', '12', '6'], ans: 3, diff: 'HARD', r: 'Excellent advanced reasoning.', w: '3 intersection points × 4 angles = 12.' },
        { q: 'If ∠1:∠2 = 2:7 and they are co-interior, ∠1 =:', op: ['40°', '20°', '60°', '80°'], ans: 1, diff: 'HARD', r: 'Great ratio + geometry.', w: '2x+7x=180 → x=20, ∠1=40°.' },
    ],
    Challenge: [
        { q: 'Euclid\'s parallel postulate states:', op: ['Lines always meet', 'One parallel through point', 'No parallels exist', 'Lines are curved'], ans: 2, diff: 'EASY', r: 'Excellent history knowledge.', w: 'One unique parallel through external point.' },
        { q: 'Railway tracks are an example of:', op: ['Perpendicular lines', 'Parallel lines', 'Intersecting lines', 'Curved lines'], ans: 2, diff: 'EASY', r: 'Good real-world connect.', w: 'Tracks are parallel.' },
        { q: 'If two lines are cut by transversal making equal corresponding angles they are:', op: ['Perpendicular', 'Parallel', 'Skew', 'Concurrent'], ans: 2, diff: 'EASY', r: 'Accurate converse theorem.', w: 'Equal corresponding angles → parallel.' },
        { q: 'Supplementary angles sum to:', op: ['90°', '180°', '360°', '45°'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'Supplementary = 180°.' },
        { q: 'Complementary angles sum to:', op: ['90°', '180°', '360°', '45°'], ans: 1, diff: 'EASY', r: 'Accurate.', w: 'Complementary = 90°.' },
        { q: 'If ∠x and ∠y are alternate and ∠x = 5a+15, ∠y = 3a+45, find a:', op: ['15', '10', '20', '25'], ans: 1, diff: 'MEDIUM', r: 'Excellent algebraic skills.', w: '5a+15=3a+45 → a=15.' },
        { q: 'Angle bisector of 120° makes angle of:', op: ['30°', '60°', '90°', '45°'], ans: 2, diff: 'MEDIUM', r: 'Good bisector concept.', w: '120°/2 = 60°.' },
        { q: 'If exterior angle is 140°, interior angle on same side is:', op: ['140°', '40°', '50°', '90°'], ans: 2, diff: 'MEDIUM', r: 'Strong calculation.', w: '180° − 140° = 40°.' },
        { q: 'Two angles are 3x+5 and 7x−25, co-interior. x =:', op: ['20', '15', '25', '10'], ans: 1, diff: 'HARD', r: 'Excellent problem-solving.', w: '3x+5+7x−25=180 → x=20.' },
        { q: 'In a triangle with one side extended, exterior angle equals:', op: ['Adjacent interior', 'Sum of remote interiors', 'Half of sum', 'None'], ans: 2, diff: 'HARD', r: 'Great theorem knowledge.', w: 'Exterior angle = sum of remote interior angles.' },
    ],
};

// ========== CHAPTER 3: Indices and Cube Root ==========
const ch3: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: '2³ equals:', op: ['6', '8', '9', '4'], ans: 2, diff: 'EASY', r: 'Good basic power.', w: '2³ = 2×2×2 = 8.' },
        { q: '5⁰ equals:', op: ['0', '5', '1', '50'], ans: 3, diff: 'EASY', r: 'Excellent rule recall.', w: 'Any number⁰ = 1.' },
        { q: '10² equals:', op: ['20', '100', '1000', '10'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '10² = 100.' },
        { q: 'Cube root of 27 is:', op: ['3', '9', '27', '6'], ans: 1, diff: 'EASY', r: 'Good cube root knowledge.', w: '3³ = 27, so ∛27 = 3.' },
        { q: 'Which is a perfect cube?', op: ['8', '10', '12', '15'], ans: 1, diff: 'EASY', r: 'Correct identification.', w: '8 = 2³ is a perfect cube.' },
        { q: 'aᵐ × aⁿ equals:', op: ['aᵐ⁺ⁿ', 'aᵐⁿ', 'aᵐ⁻ⁿ', '2aᵐ'], ans: 1, diff: 'MEDIUM', r: 'Strong index law.', w: 'Same base: add exponents.' },
        { q: 'aᵐ ÷ aⁿ equals:', op: ['aᵐ⁺ⁿ', 'aᵐⁿ', 'aᵐ⁻ⁿ', 'aᵐ/ⁿ'], ans: 3, diff: 'MEDIUM', r: 'Good rule application.', w: 'Same base division: subtract exponents.' },
        { q: '(2³)² equals:', op: ['2⁵', '2⁶', '2⁹', '2¹'], ans: 2, diff: 'MEDIUM', r: 'Excellent power of power.', w: '(aᵐ)ⁿ = aᵐⁿ = 2⁶.' },
        { q: '∛125 equals:', op: ['5', '25', '15', '10'], ans: 1, diff: 'HARD', r: 'Strong cube root.', w: '5³ = 125.' },
        { q: '2⁻³ equals:', op: ['−8', '1/8', '8', '−1/8'], ans: 2, diff: 'HARD', r: 'Excellent negative index.', w: '2⁻³ = 1/2³ = 1/8.' },
    ],
    Beginner: [
        { q: '3² equals:', op: ['6', '9', '27', '3'], ans: 2, diff: 'EASY', r: 'Good basic power.', w: '3² = 9.' },
        { q: '4³ equals:', op: ['12', '16', '64', '48'], ans: 3, diff: 'EASY', r: 'Accurate.', w: '4³ = 64.' },
        { q: 'a¹ equals:', op: ['0', '1', 'a', 'a²'], ans: 3, diff: 'EASY', r: 'Good rule.', w: 'Any number¹ = itself.' },
        { q: 'Cube root of 64 is:', op: ['2', '4', '8', '16'], ans: 2, diff: 'EASY', r: 'Correct.', w: '4³ = 64.' },
        { q: '∛1 equals:', op: ['0', '1', '−1', 'Undefined'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '1³ = 1.' },
        { q: '2⁴ × 2³ equals:', op: ['2⁷', '2¹²', '4⁷', '2¹'], ans: 1, diff: 'MEDIUM', r: 'Good law of indices.', w: '2⁴⁺³ = 2⁷.' },
        { q: '5³ ÷ 5² equals:', op: ['5⁵', '5¹', '5⁶', '1'], ans: 2, diff: 'MEDIUM', r: 'Strong division rule.', w: '5³⁻² = 5¹ = 5.' },
        { q: '(3²)³ equals:', op: ['3⁵', '3⁶', '3⁸', '9³'], ans: 2, diff: 'MEDIUM', r: 'Excellent power rule.', w: '(3²)³ = 3⁶.' },
        { q: '∛216 equals:', op: ['6', '36', '12', '18'], ans: 1, diff: 'HARD', r: 'Excellent cube root.', w: '6³ = 216.' },
        { q: '(−2)³ equals:', op: ['8', '−8', '6', '−6'], ans: 2, diff: 'HARD', r: 'Good sign handling.', w: '(−2)³ = −8 (odd power stays negative).' },
    ],
    Intermediate: [
        { q: '1⁰⁰ equals:', op: ['0', '100', '1', 'Undefined'], ans: 3, diff: 'EASY', r: 'Good rule.', w: '1 raised to any power = 1.' },
        { q: '∛8 equals:', op: ['2', '4', '8', '16'], ans: 1, diff: 'EASY', r: 'Accurate.', w: '2³ = 8.' },
        { q: 'Which is a perfect cube?', op: ['9', '16', '27', '25'], ans: 3, diff: 'EASY', r: 'Good identification.', w: '27 = 3³.' },
        { q: '(ab)² equals:', op: ['a²b²', 'ab²', 'a²b', '2ab'], ans: 1, diff: 'EASY', r: 'Correct rule.', w: '(ab)ⁿ = aⁿbⁿ.' },
        { q: '10³ equals:', op: ['30', '100', '1000', '10000'], ans: 3, diff: 'EASY', r: 'Good recall.', w: '10³ = 1000.' },
        { q: 'Simplify: 3⁵ × 3⁻² =', op: ['3³', '3⁷', '3¹⁰', '3⁻³'], ans: 1, diff: 'MEDIUM', r: 'Good negative index.', w: '3⁵⁺⁽⁻²⁾ = 3³.' },
        { q: '(a/b)³ equals:', op: ['a³/b³', '3a/3b', 'a/b³', 'a³/b'], ans: 1, diff: 'MEDIUM', r: 'Strong fraction power.', w: '(a/b)ⁿ = aⁿ/bⁿ.' },
        { q: '∛1000 equals:', op: ['10', '100', '31', '33'], ans: 1, diff: 'MEDIUM', r: 'Accurate.', w: '10³ = 1000.' },
        { q: 'If 2ˣ = 32, x =:', op: ['4', '5', '6', '3'], ans: 2, diff: 'HARD', r: 'Excellent equation solving.', w: '2⁵ = 32.' },
        { q: '∛(−64) equals:', op: ['4', '−4', '8', '−8'], ans: 2, diff: 'HARD', r: 'Good negative cube root.', w: '(−4)³ = −64.' },
    ],
    Advance: [
        { q: 'a⁻¹ equals:', op: ['−a', '1/a', 'a', '0'], ans: 2, diff: 'EASY', r: 'Good reciprocal concept.', w: 'a⁻¹ = 1/a.' },
        { q: '(2/3)² equals:', op: ['4/9', '2/9', '4/6', '2/3'], ans: 1, diff: 'EASY', r: 'Accurate.', w: '(2/3)² = 4/9.' },
        { q: '7⁰ + 3⁰ equals:', op: ['0', '1', '2', '10'], ans: 3, diff: 'EASY', r: 'Excellent rule application.', w: '7⁰=1, 3⁰=1, sum=2.' },
        { q: '∛343 equals:', op: ['7', '49', '17', '21'], ans: 1, diff: 'EASY', r: 'Good cube root.', w: '7³ = 343.' },
        { q: '(−3)² equals:', op: ['9', '−9', '6', '−6'], ans: 1, diff: 'EASY', r: 'Correct sign rule.', w: 'Even power → positive.' },
        { q: 'Simplify: (2³ × 3²) ÷ (2² × 3) =', op: ['6', '12', '18', '3'], ans: 1, diff: 'MEDIUM', r: 'Excellent simplification.', w: '2¹ × 3¹ = 6.' },
        { q: 'If 3ˣ = 81, x =:', op: ['2', '3', '4', '5'], ans: 3, diff: 'MEDIUM', r: 'Good equation solving.', w: '3⁴ = 81.' },
        { q: '(5⁻²)⁻¹ equals:', op: ['5²', '5⁻²', '25', '1/25'], ans: 1, diff: 'MEDIUM', r: 'Strong negative index.', w: '(5⁻²)⁻¹ = 5² = 25.' },
        { q: '∛(27 × 8) equals:', op: ['6', '15', '12', '21'], ans: 1, diff: 'HARD', r: 'Excellent property: ∛(ab)=∛a×∛b.', w: '∛27 × ∛8 = 3×2 = 6.' },
        { q: 'Express 0.001 as power of 10:', op: ['10⁻²', '10⁻³', '10³', '10⁻¹'], ans: 2, diff: 'HARD', r: 'Strong scientific notation.', w: '0.001 = 10⁻³.' },
    ],
    Challenge: [
        { q: 'Standard form of 5000 is:', op: ['5×10²', '5×10³', '50×10²', '0.5×10⁴'], ans: 2, diff: 'EASY', r: 'Good standard form.', w: '5000 = 5×10³.' },
        { q: '2⁵ equals:', op: ['10', '16', '32', '64'], ans: 3, diff: 'EASY', r: 'Accurate.', w: '2⁵ = 32.' },
        { q: '∛512 equals:', op: ['8', '64', '12', '16'], ans: 1, diff: 'EASY', r: 'Correct cube root.', w: '8³ = 512.' },
        { q: '(−1)⁵⁰ equals:', op: ['−1', '1', '50', '0'], ans: 2, diff: 'EASY', r: 'Good sign rule.', w: 'Even power of −1 = 1.' },
        { q: '(10²)³ equals:', op: ['10⁵', '10⁶', '10⁸', '10⁹'], ans: 2, diff: 'EASY', r: 'Strong power of power.', w: '(10²)³ = 10⁶.' },
        { q: 'Simplify: 2⁵ × 2⁻³ × 2² =', op: ['2⁴', '2¹⁰', '2⁰', '2²'], ans: 1, diff: 'MEDIUM', r: 'Excellent index manipulation.', w: '5+(−3)+2 = 4, so 2⁴.' },
        { q: 'If x³ = −125, x =:', op: ['5', '−5', '25', '−25'], ans: 2, diff: 'MEDIUM', r: 'Good equation solving.', w: '(−5)³ = −125.' },
        { q: '∛(0.008) equals:', op: ['0.2', '0.02', '0.8', '2'], ans: 1, diff: 'MEDIUM', r: 'Excellent decimal cube root.', w: '0.2³ = 0.008.' },
        { q: 'Simplify: (8/27)^(1/3) =', op: ['2/3', '8/3', '2/9', '4/9'], ans: 1, diff: 'HARD', r: 'Outstanding fractional power.', w: '∛8/∛27 = 2/3.' },
        { q: 'If 2ˣ⁺¹ = 64, x =:', op: ['4', '5', '6', '3'], ans: 2, diff: 'HARD', r: 'Excellent equation mastery.', w: '2⁶=64, so x+1=6, x=5.' },
    ],
};


// ========== CHAPTER 4: Altitudes and Medians of a Triangle ==========
const ch4: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'An altitude of a triangle is:', op: ['Perpendicular to base', 'Parallel to base', 'Equal to base', 'Half of base'], ans: 1, diff: 'EASY', r: 'Correct!', w: 'Altitude is perpendicular from vertex to base.' },
        { q: 'A median connects vertex to:', op: ['Midpoint of opposite side', 'Any point', 'Adjacent vertex', 'Centre'], ans: 1, diff: 'EASY', r: 'Excellent recall.', w: 'Median goes to midpoint of opposite side.' },
        { q: 'How many altitudes does a triangle have?', op: ['1', '2', '3', '4'], ans: 3, diff: 'EASY', r: 'Good accuracy.', w: 'Every triangle has 3 altitudes.' },
        { q: 'How many medians does a triangle have?', op: ['1', '2', '3', '6'], ans: 3, diff: 'EASY', r: 'Accurate.', w: '3 medians, one from each vertex.' },
        { q: 'The point where all 3 medians meet is called:', op: ['Orthocentre', 'Centroid', 'Incentre', 'Circumcentre'], ans: 2, diff: 'EASY', r: 'Strong concept.', w: 'Medians meet at centroid.' },
        { q: 'The point where all 3 altitudes meet is called:', op: ['Centroid', 'Orthocentre', 'Incentre', 'Circumcentre'], ans: 2, diff: 'MEDIUM', r: 'Good identification.', w: 'Altitudes meet at orthocentre.' },
        { q: 'Centroid divides median in ratio:', op: ['1:1', '1:2', '2:1', '3:1'], ans: 3, diff: 'MEDIUM', r: 'Excellent property.', w: 'Centroid divides median 2:1 from vertex.' },
        { q: 'In a right triangle, altitude from right angle falls on:', op: ['Outside', 'Hypotenuse', 'Shortest side', 'Longest side only'], ans: 2, diff: 'MEDIUM', r: 'Good understanding.', w: 'Altitude falls on hypotenuse.' },
        { q: 'Orthocentre of a right triangle lies:', op: ['Inside', 'Outside', 'At right-angle vertex', 'At centroid'], ans: 3, diff: 'HARD', r: 'Excellent advanced knowledge.', w: 'Orthocentre is at the right angle vertex.' },
        { q: 'In an equilateral triangle, altitude and median are:', op: ['Different', 'Same', 'Perpendicular', 'Parallel'], ans: 2, diff: 'HARD', r: 'Strong reasoning.', w: 'In equilateral triangle, altitude = median.' },
    ],
    Beginner: [
        { q: 'Altitude makes what angle with the base?', op: ['45°', '60°', '90°', '180°'], ans: 3, diff: 'EASY', r: 'Good recall.', w: 'Altitude is perpendicular = 90°.' },
        { q: 'Median divides opposite side into:', op: ['Unequal parts', '2 equal parts', '3 parts', '4 parts'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Median bisects opposite side.' },
        { q: 'In an obtuse triangle, orthocentre lies:', op: ['Inside', 'Outside', 'On a vertex', 'At centre'], ans: 2, diff: 'EASY', r: 'Good concept.', w: 'Orthocentre is outside for obtuse triangles.' },
        { q: 'Centroid always lies:', op: ['Outside', 'Inside', 'On a side', 'At vertex'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Centroid always lies inside.' },
        { q: 'The altitude is also called:', op: ['Height', 'Base', 'Diagonal', 'Median'], ans: 1, diff: 'EASY', r: 'Good terminology.', w: 'Altitude = height.' },
        { q: 'If median is 9 cm, centroid to vertex is:', op: ['3 cm', '6 cm', '4.5 cm', '9 cm'], ans: 2, diff: 'MEDIUM', r: 'Good ratio application.', w: '2/3 of 9 = 6 cm.' },
        { q: 'If median is 12 cm, centroid to midpoint is:', op: ['4 cm', '6 cm', '8 cm', '3 cm'], ans: 1, diff: 'MEDIUM', r: 'Excellent calculation.', w: '1/3 of 12 = 4 cm.' },
        { q: 'In isosceles triangle, median to base is also:', op: ['Altitude', 'Diagonal', 'Parallel', 'Transversal'], ans: 1, diff: 'MEDIUM', r: 'Strong understanding.', w: 'Median to base = altitude in isosceles.' },
        { q: 'How many concurrent points do medians form?', op: ['0', '1', '2', '3'], ans: 2, diff: 'HARD', r: 'Excellent concurrence concept.', w: 'All 3 medians meet at 1 point.' },
        { q: 'Centroid divides triangle into how many equal-area triangles?', op: ['2', '3', '6', '4'], ans: 3, diff: 'HARD', r: 'Outstanding property.', w: 'Centroid creates 6 equal-area triangles.' },
    ],
    Intermediate: [
        { q: 'Altitude can lie outside in:', op: ['Acute', 'Right', 'Obtuse', 'Equilateral'], ans: 3, diff: 'EASY', r: 'Good understanding.', w: 'In obtuse triangles, altitude can be outside.' },
        { q: 'The centroid is also called:', op: ['Centre of gravity', 'Circumcentre', 'Incentre', 'Excentre'], ans: 1, diff: 'EASY', r: 'Correct terminology.', w: 'Centroid = centre of gravity.' },
        { q: 'A triangle has how many orthocentres?', op: ['0', '1', '2', '3'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Only 1 orthocentre per triangle.' },
        { q: 'In acute triangle, orthocentre lies:', op: ['Inside', 'Outside', 'On hypotenuse', 'At vertex'], ans: 1, diff: 'EASY', r: 'Good recall.', w: 'Inside for acute triangles.' },
        { q: 'Median and altitude same in:', op: ['Scalene', 'Isosceles only', 'Equilateral', 'Right'], ans: 3, diff: 'EASY', r: 'Correct.', w: 'In equilateral, they coincide.' },
        { q: 'If median from A is 15 cm, AG =:', op: ['5 cm', '10 cm', '7.5 cm', '15 cm'], ans: 2, diff: 'MEDIUM', r: 'Good ratio.', w: 'AG = 2/3 × 15 = 10 cm.' },
        { q: 'In equilateral triangle side 6, median =:', op: ['3', '3√3', '6', '2√3'], ans: 2, diff: 'MEDIUM', r: 'Strong formula.', w: 'Median = (√3/2)×6 = 3√3.' },
        { q: 'Sum of angles at orthocentre:', op: ['180°', '360°', '90°', '270°'], ans: 2, diff: 'MEDIUM', r: 'Excellent reasoning.', w: 'Angles around a point = 360°.' },
        { q: 'Altitude from A to BC is denoted:', op: ['ma', 'ha', 'la', 'da'], ans: 2, diff: 'HARD', r: 'Good notation.', w: 'ha denotes altitude from A.' },
        { q: 'Area of triangle = ½ × base ×:', op: ['Side', 'Median', 'Altitude', 'Diagonal'], ans: 3, diff: 'HARD', r: 'Excellent formula.', w: 'Area = ½ × base × altitude.' },
    ],
    Advance: [
        { q: 'In right triangle, how many altitudes lie on sides?', op: ['0', '1', '2', '3'], ans: 3, diff: 'EASY', r: 'Great visualization.', w: 'Two legs serve as altitudes.' },
        { q: 'Circumcentre of right triangle lies on:', op: ['Inside', 'Outside', 'Hypotenuse midpoint', 'Vertex'], ans: 3, diff: 'EASY', r: 'Excellent.', w: 'Circumcentre = midpoint of hypotenuse.' },
        { q: 'Foot of altitude is:', op: ['The vertex', 'Point where altitude meets base', 'Centroid', 'Midpoint'], ans: 2, diff: 'EASY', r: 'Good definition.', w: 'Foot = where altitude meets base.' },
        { q: 'Centroid coordinates use:', op: ['Sum/3', 'Sum/2', 'Product', 'Difference'], ans: 1, diff: 'EASY', r: 'Good formula.', w: 'Centroid = ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3).' },
        { q: 'In scalene triangle, all medians are:', op: ['Equal', 'Unequal', 'Zero', 'Parallel'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Unequal sides → unequal medians.' },
        { q: 'If G is centroid and GD = 4, median AD =:', op: ['8', '12', '6', '16'], ans: 2, diff: 'MEDIUM', r: 'Good ratio.', w: 'GD = 1/3 of AD → AD = 12.' },
        { q: 'Orthocentre, centroid, circumcentre lie on:', op: ['Euler line', 'Median', 'Altitude', 'Base'], ans: 1, diff: 'MEDIUM', r: 'Excellent advanced knowledge.', w: 'They lie on Euler line.' },
        { q: 'In equilateral △, centroid and orthocentre:', op: ['Different', 'Same point', 'Opposite', 'Parallel'], ans: 2, diff: 'MEDIUM', r: 'Strong understanding.', w: 'All centres coincide in equilateral △.' },
        { q: 'If △ has vertices (0,0),(6,0),(3,6), centroid is:', op: ['(3,2)', '(3,3)', '(2,3)', '(4,2)'], ans: 1, diff: 'HARD', r: 'Excellent coordinate geometry.', w: '((0+6+3)/3,(0+0+6)/3)=(3,2).' },
        { q: 'Three medians divide triangle into:', op: ['3 triangles', '6 triangles', '4 triangles', '2 triangles'], ans: 2, diff: 'HARD', r: 'Strong knowledge.', w: '3 medians create 6 smaller triangles.' },
    ],
    Challenge: [
        { q: 'Which always passes through vertex?', op: ['Perpendicular bisector', 'Median and Altitude', 'Only median', 'All'], ans: 2, diff: 'EASY', r: 'Great distinction.', w: 'Median and altitude start from vertex.' },
        { q: 'Centroid divides median in ratio from vertex:', op: ['1:1', '2:1', '3:1', '1:2'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '2:1 from vertex.' },
        { q: 'Longest median is opposite to:', op: ['Longest side', 'Shortest side', 'Equal side', 'Right angle'], ans: 2, diff: 'EASY', r: 'Excellent property.', w: 'Longest median opposite shortest side.' },
        { q: 'In acute triangle, altitudes inside:', op: ['1', '2', '3', '0'], ans: 3, diff: 'EASY', r: 'Good visualization.', w: 'All 3 altitudes inside for acute.' },
        { q: 'In obtuse triangle, altitudes outside:', op: ['0', '1', '2', '3'], ans: 3, diff: 'EASY', r: 'Strong concept.', w: '2 altitudes fall outside in obtuse.' },
        { q: 'Midpoint of B(0,0),C(8,0) is:', op: ['(4,0)', '(0,4)', '(8,0)', '(2,0)'], ans: 1, diff: 'MEDIUM', r: 'Good midpoint.', w: '((0+8)/2,0)=(4,0).' },
        { q: 'If altitude=10, base=12, area=:', op: ['60', '120', '30', '24'], ans: 1, diff: 'MEDIUM', r: 'Excellent area calculation.', w: '½×12×10=60.' },
        { q: 'Medians divide triangle into:', op: ['3 triangles', '6 triangles', '4 triangles', '2 triangles'], ans: 2, diff: 'MEDIUM', r: 'Strong knowledge.', w: '6 smaller triangles.' },
        { q: 'If centroid G, PG=8, then median PM=:', op: ['12', '16', '24', '10'], ans: 1, diff: 'HARD', r: 'Excellent ratio mastery.', w: 'PG=2/3 PM → PM=12.' },
        { q: 'Orthocentre of equilateral △ with vertices (0,0),(6,0),(3,3√3):', op: ['(3,√3)', '(3,3)', '(0,0)', '(3,2√3)'], ans: 1, diff: 'HARD', r: 'Outstanding coordinate geometry.', w: 'In equilateral, orthocentre=centroid=(3,√3).' },
    ],
};

// ========== CHAPTER 5: Expansion Formulae ==========
const ch5: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: '(a+b)² equals:', op: ['a²+b²', 'a²+2ab+b²', 'a²−2ab+b²', '2a+2b'], ans: 2, diff: 'EASY', r: 'Correct formula!', w: '(a+b)² = a²+2ab+b².' },
        { q: '(a−b)² equals:', op: ['a²−b²', 'a²+2ab+b²', 'a²−2ab+b²', 'a−b'], ans: 3, diff: 'EASY', r: 'Good recall.', w: '(a−b)² = a²−2ab+b².' },
        { q: '(a+b)(a−b) equals:', op: ['a²+b²', 'a²−b²', '2ab', 'a²+2ab+b²'], ans: 2, diff: 'EASY', r: 'Excellent identity.', w: 'Difference of squares: a²−b².' },
        { q: '(x+3)² equals:', op: ['x²+9', 'x²+3x+9', 'x²+6x+9', 'x²+6x+3'], ans: 3, diff: 'EASY', r: 'Good application.', w: '(x+3)² = x²+6x+9.' },
        { q: '(2+3)² equals:', op: ['10', '13', '25', '11'], ans: 3, diff: 'EASY', r: 'Accurate.', w: '5² = 25.' },
        { q: '(x−5)² equals:', op: ['x²−25', 'x²−10x+25', 'x²+10x+25', 'x²−5x+25'], ans: 2, diff: 'MEDIUM', r: 'Good expansion.', w: '(x−5)² = x²−10x+25.' },
        { q: '(2x+3)² equals:', op: ['4x²+9', '4x²+6x+9', '4x²+12x+9', '2x²+12x+9'], ans: 3, diff: 'MEDIUM', r: 'Excellent coefficient handling.', w: '(2x)²+2(2x)(3)+3² = 4x²+12x+9.' },
        { q: '(a+b)²−(a−b)² equals:', op: ['2ab', '4ab', '2a²', '2b²'], ans: 2, diff: 'MEDIUM', r: 'Strong identity.', w: 'Expand both and subtract: 4ab.' },
        { q: '101² using expansion:', op: ['10000', '10201', '10101', '10200'], ans: 2, diff: 'HARD', r: 'Excellent shortcut.', w: '(100+1)² = 10000+200+1 = 10201.' },
        { q: '99² using expansion:', op: ['9801', '9800', '9901', '9810'], ans: 1, diff: 'HARD', r: 'Great mental math!', w: '(100−1)² = 10000−200+1 = 9801.' },
    ],
    Beginner: [
        { q: 'In (a+b)², the middle term is:', op: ['a²', 'b²', '2ab', 'ab'], ans: 3, diff: 'EASY', r: 'Good identification.', w: 'Middle term = 2ab.' },
        { q: '(p+q)² when p=2, q=1:', op: ['5', '9', '6', '4'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '(2+1)² = 9.' },
        { q: '(a+0)² equals:', op: ['a', '0', 'a²', '2a'], ans: 3, diff: 'EASY', r: 'Good understanding.', w: '(a+0)² = a².' },
        { q: 'a²−b² is called:', op: ['Sum of squares', 'Difference of squares', 'Perfect square', 'Cube'], ans: 2, diff: 'EASY', r: 'Correct terminology.', w: 'a²−b² = difference of squares.' },
        { q: '(x+1)(x−1) equals:', op: ['x²−1', 'x²+1', 'x²−x', '2x'], ans: 1, diff: 'EASY', r: 'Excellent identity.', w: 'x²−1.' },
        { q: '(3a+2b)² equals:', op: ['9a²+4b²', '9a²+6ab+4b²', '9a²+12ab+4b²', '3a²+12ab+2b²'], ans: 3, diff: 'MEDIUM', r: 'Good expansion.', w: '9a²+12ab+4b².' },
        { q: '(x−4)(x+4) equals:', op: ['x²−16', 'x²+16', 'x²−8x', 'x²−4'], ans: 1, diff: 'MEDIUM', r: 'Strong identity.', w: 'x²−16.' },
        { q: '(a+b)²+(a−b)² equals:', op: ['2a²', '2b²', '2a²+2b²', '4ab'], ans: 3, diff: 'MEDIUM', r: 'Excellent combination.', w: 'Expand and add: 2a²+2b².' },
        { q: '52 × 48 using identity:', op: ['2496', '2500', '2400', '2504'], ans: 1, diff: 'HARD', r: 'Excellent application.', w: '(50+2)(50−2)=2500−4=2496.' },
        { q: 'If (x+1/x)=5, x²+1/x²=:', op: ['23', '25', '27', '21'], ans: 1, diff: 'HARD', r: 'Outstanding algebra.', w: '(x+1/x)²=x²+2+1/x² → 25−2=23.' },
    ],
    Intermediate: [
        { q: '(a+b+c)² has how many terms?', op: ['3', '6', '9', '4'], ans: 2, diff: 'EASY', r: 'Good knowledge.', w: 'a²+b²+c²+2ab+2bc+2ca = 6 terms.' },
        { q: '(x+2)² − x² equals:', op: ['4', '4x+4', '2x+4', '4x'], ans: 2, diff: 'EASY', r: 'Good expansion.', w: 'x²+4x+4−x² = 4x+4.' },
        { q: '(5)² − (3)² equals:', op: ['16', '4', '8', '34'], ans: 1, diff: 'EASY', r: 'Correct.', w: '25−9 = 16.' },
        { q: '(a+b)² is always:', op: ['Negative', 'Zero', 'Positive or zero', 'Negative or zero'], ans: 3, diff: 'EASY', r: 'Good understanding.', w: 'Squares are always ≥ 0.' },
        { q: '(1+1)² equals:', op: ['2', '3', '4', '1'], ans: 3, diff: 'EASY', r: 'Accurate.', w: '2² = 4.' },
        { q: 'Expand (2x−3y)²:', op: ['4x²−9y²', '4x²−6xy+9y²', '4x²−12xy+9y²', '2x²−12xy+9y²'], ans: 3, diff: 'MEDIUM', r: 'Excellent expansion.', w: '4x²−12xy+9y².' },
        { q: '(x+y)(x−y) when x=7,y=3:', op: ['40', '10', '21', '49'], ans: 1, diff: 'MEDIUM', r: 'Good mental math.', w: '49−9 = 40.' },
        { q: '(a+b)³ expands to:', op: ['a³+3a²b+3ab²+b³', 'a³+b³', 'a³−b³', '3ab'], ans: 1, diff: 'MEDIUM', r: 'Strong cube expansion.', w: '(a+b)³ = a³+3a²b+3ab²+b³.' },
        { q: '(x+3)(x+5) using identity:', op: ['x²+8x+15', 'x²+8x+8', 'x²+15x+8', 'x²+5x+3'], ans: 1, diff: 'HARD', r: 'Excellent identity.', w: 'x²+(3+5)x+15 = x²+8x+15.' },
        { q: 'If a+b=10, ab=21, a²+b²=:', op: ['58', '79', '100', '42'], ans: 1, diff: 'HARD', r: 'Outstanding manipulation.', w: '(a+b)²=a²+2ab+b² → 100−42=58.' },
    ],
    Advance: [
        { q: 'Factored form of a²−b²:', op: ['(a−b)²', '(a+b)²', '(a+b)(a−b)', '(a−b)(a+b+1)'], ans: 3, diff: 'EASY', r: 'Good factoring.', w: 'a²−b² = (a+b)(a−b).' },
        { q: '(−a+b)² equals:', op: ['a²+2ab+b²', 'a²−2ab+b²', '−a²+b²', 'b²−a²'], ans: 2, diff: 'EASY', r: 'Good sign handling.', w: '(b−a)² = a²−2ab+b².' },
        { q: '(x+y+z)² includes term:', op: ['2xyz', '2xy', '3xy', 'x²y²'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Includes 2xy, 2yz, 2xz terms.' },
        { q: '(10+2)² = 10²+2(10)(2)+2² =:', op: ['120', '144', '124', '140'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '100+40+4 = 144.' },
        { q: '(a−b)² is always:', op: ['Negative', 'Positive or zero', 'Zero', 'Undefined'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Any square ≥ 0.' },
        { q: 'Expand (3x+4)(3x−4):', op: ['9x²−16', '9x²+16', '9x²−8x', '9x²+24x−16'], ans: 1, diff: 'MEDIUM', r: 'Excellent.', w: '(3x)²−4² = 9x²−16.' },
        { q: 'If a−b=3, ab=10, a²+b²=:', op: ['29', '19', '9', '39'], ans: 1, diff: 'MEDIUM', r: 'Strong manipulation.', w: '(a−b)²=a²−2ab+b² → 9+20=29.' },
        { q: '(x+1/x)² equals:', op: ['x²+1/x²', 'x²+2+1/x²', 'x²+1+1/x²', 'x²−2+1/x²'], ans: 2, diff: 'MEDIUM', r: 'Excellent expansion.', w: 'x²+2+1/x².' },
        { q: '(a+b)³ − (a−b)³ equals:', op: ['2b³', '2b(3a²+b²)', '6a²b', '2a³'], ans: 2, diff: 'HARD', r: 'Outstanding cube identity.', w: 'Expand and subtract: 2b(3a²+b²).' },
        { q: 'If x²+1/x²=27, (x−1/x)²=:', op: ['25', '23', '29', '27'], ans: 1, diff: 'HARD', r: 'Excellent reasoning.', w: 'x²−2+1/x²=27−2=25.' },
    ],
    Challenge: [
        { q: '(a+b)²−2ab equals:', op: ['a²+b²', 'a²−b²', '2a²', '(a−b)²'], ans: 1, diff: 'EASY', r: 'Good identity.', w: 'a²+2ab+b²−2ab = a²+b².' },
        { q: '103² using (100+3)²:', op: ['10609', '10600', '10309', '10603'], ans: 1, diff: 'EASY', r: 'Excellent shortcut.', w: '10000+600+9 = 10609.' },
        { q: '97 × 103 using identity:', op: ['9991', '10000', '10006', '9909'], ans: 1, diff: 'EASY', r: 'Great mental math.', w: '(100−3)(100+3)=10000−9=9991.' },
        { q: '(2a)² equals:', op: ['2a²', '4a²', '4a', '2a'], ans: 2, diff: 'EASY', r: 'Good squaring.', w: '(2a)² = 4a².' },
        { q: 'If a=b in (a+b)², result:', op: ['2a²', '4a²', 'a²', 'a⁴'], ans: 2, diff: 'EASY', r: 'Good substitution.', w: '(2a)²=4a².' },
        { q: 'Simplify (x+3)²−(x−3)²:', op: ['12x', '6x', '9', '18'], ans: 1, diff: 'MEDIUM', r: 'Excellent identity.', w: '4ab → 4(x)(3)=12x.' },
        { q: 'If a²+b²=50, ab=7, (a+b)²=:', op: ['64', '57', '43', '36'], ans: 1, diff: 'MEDIUM', r: 'Strong formula.', w: 'a²+2ab+b²=50+14=64.' },
        { q: '995² equals:', op: ['990025', '990000', '990050', '989025'], ans: 1, diff: 'MEDIUM', r: 'Excellent mental math.', w: '(1000−5)²=1000000−10000+25=990025.' },
        { q: 'If (a+b+c)²=100, a²+b²+c²=40, ab+bc+ca=:', op: ['30', '60', '20', '50'], ans: 1, diff: 'HARD', r: 'Outstanding mastery.', w: '100=40+2(ab+bc+ca) → 30.' },
        { q: '(x²+1/x²)−(x−1/x)² equals:', op: ['0', '2', '−2', '1'], ans: 2, diff: 'HARD', r: 'Excellent skills.', w: 'x²+1/x²−(x²−2+1/x²) = 2.' },
    ],
};

export const mathChaptersData: ChapterData[] = [
    { name: 'Rational and Irrational Numbers', order: 1, levels: makeLevels(ch1), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBYgDuCkYL3YntehJ3ldWBA5&si=DXxyroqha1RJFZfT' },
    { name: 'Parallel Lines and Transversal', order: 2, levels: makeLevels(ch2), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBYgDuCkYL3YntehJ3ldWBA5&si=DXxyroqha1RJFZfT' },
    { name: 'Indices and Cube Root', order: 3, levels: makeLevels(ch3), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBYgDuCkYL3YntehJ3ldWBA5&si=DXxyroqha1RJFZfT' },
    { name: 'Altitudes and Medians of a Triangle', order: 4, levels: makeLevels(ch4), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBYgDuCkYL3YntehJ3ldWBA5&si=DXxyroqha1RJFZfT' },
    { name: 'Expansion Formulae', order: 5, levels: makeLevels(ch5), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBYgDuCkYL3YntehJ3ldWBA5&si=DXxyroqha1RJFZfT' },
];

