import { QuestionData, LevelData, ChapterData } from './mathChapters.js';

function makeLevels(topics: Record<string, QuestionData[]>): LevelData[] {
    return ['Diagnostic', 'Beginner', 'Intermediate', 'Advance', 'Challenge'].map(n => ({ name: n, questions: topics[n] }));
}

// ========== CHAPTER 1: Living World and Classification of Microbes ==========
const ch1: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Biological classification means:', op: ['Naming only', 'Grouping organisms', 'Eating food', 'Movement'], ans: 2, diff: 'EASY', r: 'Excellent speed and accuracy.', w: 'Classification means grouping.' },
        { q: 'Total kingdoms in five-kingdom system:', op: ['2', '3', '5', '7'], ans: 3, diff: 'EASY', r: 'Good recall.', w: 'Five kingdom system.' },
        { q: 'Monera organisms are:', op: ['Multicellular', 'Prokaryotic', 'Only plants', 'Only animals'], ans: 2, diff: 'EASY', r: 'Accurate response.', w: 'Monera are prokaryotic.' },
        { q: 'Amoeba belongs to:', op: ['Monera', 'Protista', 'Fungi', 'Animalia'], ans: 2, diff: 'EASY', r: 'Fast identification.', w: 'Amoeba is Protista.' },
        { q: 'Fungi obtain food by:', op: ['Photosynthesis', 'Absorption', 'Hunting', 'Chewing'], ans: 2, diff: 'EASY', r: 'Good accuracy.', w: 'Fungi absorb nutrients.' },
        { q: 'Bacteria reproduce by:', op: ['Budding', 'Binary fission', 'Seeds', 'Spores only'], ans: 2, diff: 'MEDIUM', r: 'Strong accuracy.', w: 'Bacteria divide by binary fission.' },
        { q: 'Protista are mostly:', op: ['Multicellular', 'Unicellular', 'Only plants', 'Only fungi'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Protista are unicellular.' },
        { q: 'Viruses are visible using:', op: ['Simple microscope', 'Compound microscope', 'Electron microscope', 'Naked eye'], ans: 3, diff: 'MEDIUM', r: 'Excellent accuracy.', w: 'Viruses need electron microscope.' },
        { q: 'Producers in ecosystem:', op: ['Animals', 'Plants', 'Fungi', 'Viruses'], ans: 2, diff: 'HARD', r: 'High accuracy.', w: 'Plants are producers.' },
        { q: 'Smallest microbes are:', op: ['Bacteria', 'Fungi', 'Virus', 'Algae'], ans: 3, diff: 'HARD', r: 'Excellent.', w: 'Viruses are smallest.' },
    ],
    Beginner: [
        { q: 'Study of microbes is called:', op: ['Botany', 'Zoology', 'Microbiology', 'Physics'], ans: 3, diff: 'EASY', r: 'Good accuracy.', w: 'Microbiology studies microbes.' },
        { q: 'Which is unicellular?', op: ['Mushroom', 'Amoeba', 'Human', 'Tree'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Amoeba is unicellular.' },
        { q: 'Algae are mostly:', op: ['Aquatic', 'Desert', 'Air', 'Soil only'], ans: 1, diff: 'EASY', r: 'Good accuracy.', w: 'Algae mostly live in water.' },
        { q: 'Cell wall in fungi made of:', op: ['Cellulose', 'Chitin', 'Protein', 'Fat'], ans: 2, diff: 'EASY', r: 'Excellent recall.', w: 'Fungi wall contains chitin.' },
        { q: 'Euglena is:', op: ['Bacteria', 'Protist', 'Virus', 'Animal'], ans: 2, diff: 'EASY', r: 'Strong accuracy.', w: 'Euglena belongs to Protista.' },
        { q: 'Saprotrophs feed on:', op: ['Fresh plants', 'Dead matter', 'Water', 'Air'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Saprotrophs feed on dead matter.' },
        { q: 'Which is prokaryotic?', op: ['Amoeba', 'Bacteria', 'Fungi', 'Algae'], ans: 2, diff: 'MEDIUM', r: 'Excellent.', w: 'Bacteria are prokaryotes.' },
        { q: 'Photosynthesis occurs in:', op: ['Fungi', 'Animals', 'Algae', 'Virus'], ans: 3, diff: 'MEDIUM', r: 'Good concept clarity.', w: 'Algae perform photosynthesis.' },
        { q: 'Virus contains:', op: ['Only protein', 'DNA/RNA + protein', 'Only nucleus', 'Cytoplasm'], ans: 2, diff: 'HARD', r: 'Strong accuracy.', w: 'Virus has genetic material + protein coat.' },
        { q: 'Decomposers are:', op: ['Plants', 'Fungi', 'Animals', 'Birds'], ans: 2, diff: 'HARD', r: 'Excellent.', w: 'Fungi act as decomposers.' },
    ],
    Intermediate: [
        { q: 'Five kingdom system based on:', op: ['Colour', 'Size', 'Cell and nutrition', 'Weight'], ans: 3, diff: 'EASY', r: 'Good accuracy.', w: 'Revise classification criteria.' },
        { q: 'Multicellular kingdom:', op: ['Monera', 'Protista', 'Animalia', 'Virus'], ans: 3, diff: 'EASY', r: 'Accurate.', w: 'Animals are multicellular.' },
        { q: 'Bacteria size measured in:', op: ['Meter', 'Kilometer', 'Micrometer', 'Liter'], ans: 3, diff: 'EASY', r: 'Good scientific accuracy.', w: 'Bacteria measured in micrometer.' },
        { q: 'Protozoa found in:', op: ['Space', 'Soil/water', 'Fire', 'Metal'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Protozoa live in soil & water.' },
        { q: 'Mushroom belongs to:', op: ['Fungi', 'Monera', 'Protista', 'Virus'], ans: 1, diff: 'EASY', r: 'Strong accuracy.', w: 'Mushroom is fungus.' },
        { q: 'Autotroph example:', op: ['Amoeba', 'Algae', 'Fungi', 'Virus'], ans: 2, diff: 'MEDIUM', r: 'Good clarity.', w: 'Algae are autotrophs.' },
        { q: 'Pathogenic protozoa causes:', op: ['Cold', 'Malaria', 'Fever only', 'Headache'], ans: 2, diff: 'MEDIUM', r: 'Excellent accuracy.', w: 'Plasmodium causes malaria.' },
        { q: 'Virus multiplies in:', op: ['Water', 'Air', 'Host cell', 'Soil'], ans: 3, diff: 'MEDIUM', r: 'High accuracy.', w: 'Virus needs host cell.' },
        { q: 'Which has no nucleus?', op: ['Fungi', 'Protista', 'Bacteria', 'Algae'], ans: 3, diff: 'HARD', r: 'Excellent.', w: 'Bacteria lack nucleus.' },
        { q: 'Consumers are:', op: ['Plants', 'Animals', 'Fungi', 'Algae'], ans: 2, diff: 'HARD', r: 'Strong understanding.', w: 'Animals are consumers.' },
    ],
    Advance: [
        { q: 'Producers make food by:', op: ['Digestion', 'Photosynthesis', 'Absorption', 'Hunting'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Producers photosynthesize.' },
        { q: 'Chlorella is:', op: ['Bacteria', 'Algae', 'Virus', 'Animal'], ans: 2, diff: 'EASY', r: 'Good accuracy.', w: 'Chlorella is algae.' },
        { q: 'Fungi are:', op: ['Autotroph', 'Heterotroph', 'Producers', 'None'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Fungi are heterotrophs.' },
        { q: 'Monera includes:', op: ['Virus', 'Bacteria', 'Plants', 'Animals'], ans: 2, diff: 'EASY', r: 'Excellent speed.', w: 'Monera = bacteria.' },
        { q: 'Binary fission seen in:', op: ['Plants', 'Animals', 'Bacteria', 'Birds'], ans: 3, diff: 'EASY', r: 'Accurate recall.', w: 'Bacteria divide by fission.' },
        { q: 'Virus size measured in:', op: ['Meter', 'mm', 'nm', 'cm'], ans: 3, diff: 'MEDIUM', r: 'Good accuracy.', w: 'Virus measured in nanometer.' },
        { q: 'Multicellular fungi example:', op: ['Yeast', 'Mushroom', 'Bacteria', 'Virus'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Mushroom is multicellular fungus.' },
        { q: 'Euglena shows:', op: ['Only plant trait', 'Only animal trait', 'Both', 'None'], ans: 3, diff: 'MEDIUM', r: 'High concept accuracy.', w: 'Euglena shows both traits.' },
        { q: 'Edge of living and non-living:', op: ['Fungi', 'Virus', 'Algae', 'Bacteria'], ans: 2, diff: 'HARD', r: 'Excellent knowledge.', w: 'Virus shows both properties.' },
        { q: 'Decomposer role done by:', op: ['Plants', 'Fungi', 'Birds', 'Fish'], ans: 2, diff: 'HARD', r: 'Strong concept.', w: 'Fungi decompose matter.' },
    ],
    Challenge: [
        { q: 'Classification helps in:', op: ['Confusion', 'Study organisms', 'Destroy life', 'Ignore species'], ans: 2, diff: 'EASY', r: 'Fast and accurate.', w: 'Classification helps study.' },
        { q: 'Autotroph means:', op: ['Eats others', 'Makes own food', 'No food', 'Only water'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Autotroph makes own food.' },
        { q: 'Protozoa are:', op: ['Multicellular', 'Unicellular', 'Plants', 'Virus'], ans: 2, diff: 'EASY', r: 'Good accuracy.', w: 'Protozoa unicellular.' },
        { q: 'Virus contains:', op: ['Only cell', 'Only nucleus', 'DNA or RNA', 'Roots'], ans: 3, diff: 'EASY', r: 'Excellent.', w: 'Virus has DNA/RNA.' },
        { q: 'Algae contain:', op: ['Chloroplast', 'Bone', 'Muscle', 'Hair'], ans: 1, diff: 'EASY', r: 'Correct.', w: 'Chloroplast present in algae.' },
        { q: 'Pathogenic bacteria example:', op: ['Mushroom', 'Lactobacillus', 'Salmonella', 'Algae'], ans: 3, diff: 'MEDIUM', r: 'Strong accuracy.', w: 'Salmonella causes disease.' },
        { q: 'Fungi reproduce by:', op: ['Budding/spores', 'Seeds', 'Eggs', 'Roots'], ans: 1, diff: 'MEDIUM', r: 'Excellent clarity.', w: 'Fungi reproduce by spores/budding.' },
        { q: 'Which is eukaryotic?', op: ['Bacteria', 'Virus', 'Amoeba', 'None'], ans: 3, diff: 'MEDIUM', r: 'Accurate.', w: 'Amoeba is eukaryotic.' },
        { q: 'Most numerous organisms:', op: ['Animals', 'Microorganisms', 'Plants', 'Birds'], ans: 2, diff: 'HARD', r: 'Advanced accuracy.', w: 'Microbes most numerous.' },
        { q: 'Study of classification called:', op: ['Taxonomy', 'Anatomy', 'Chemistry', 'Physics'], ans: 1, diff: 'HARD', r: 'Excellent mastery.', w: 'Taxonomy = classification study.' },
    ],
};

// ========== CHAPTER 2: Health and Diseases ==========
const ch2: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Health means:', op: ['Absence of disease only', 'Physical, mental & social well-being', 'Only physical fitness', 'Only mental fitness'], ans: 2, diff: 'EASY', r: 'Correct WHO definition.', w: 'Health = complete well-being.' },
        { q: 'Disease caused by bacteria:', op: ['Malaria', 'Tuberculosis', 'AIDS', 'Dengue'], ans: 2, diff: 'EASY', r: 'Good identification.', w: 'TB is bacterial.' },
        { q: 'Malaria is spread by:', op: ['Housefly', 'Mosquito', 'Dog', 'Cat'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Anopheles mosquito spreads malaria.' },
        { q: 'Vaccine was discovered by:', op: ['Newton', 'Edward Jenner', 'Einstein', 'Darwin'], ans: 2, diff: 'EASY', r: 'Good history.', w: 'Edward Jenner discovered vaccination.' },
        { q: 'AIDS is caused by:', op: ['Bacteria', 'Virus', 'Fungi', 'Protozoa'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'HIV virus causes AIDS.' },
        { q: 'Communicable diseases spread through:', op: ['Genetics', 'Contact/vectors', 'Exercise', 'Sleep'], ans: 2, diff: 'MEDIUM', r: 'Good understanding.', w: 'Communicable = spread by contact/vectors.' },
        { q: 'Dengue is caused by:', op: ['Bacteria', 'Protozoa', 'Virus', 'Fungi'], ans: 3, diff: 'MEDIUM', r: 'Accurate.', w: 'Dengue virus spread by Aedes mosquito.' },
        { q: 'First line of defence in body:', op: ['WBC', 'Skin', 'Bones', 'Brain'], ans: 2, diff: 'MEDIUM', r: 'Good immunity concept.', w: 'Skin is first barrier.' },
        { q: 'Antibiotic kills:', op: ['Virus', 'Bacteria', 'Both', 'None'], ans: 2, diff: 'HARD', r: 'Excellent distinction.', w: 'Antibiotics work against bacteria only.' },
        { q: 'Non-communicable disease example:', op: ['Cholera', 'Diabetes', 'Malaria', 'TB'], ans: 2, diff: 'HARD', r: 'Strong classification.', w: 'Diabetes is non-communicable.' },
    ],
    Beginner: [
        { q: 'Deficiency of iron causes:', op: ['Scurvy', 'Anaemia', 'Goitre', 'Rickets'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'Iron deficiency → anaemia.' },
        { q: 'Vitamin C prevents:', op: ['Rickets', 'Scurvy', 'Night blindness', 'Goitre'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Vitamin C prevents scurvy.' },
        { q: 'Cholera spreads through:', op: ['Air', 'Contaminated water', 'Touch', 'Light'], ans: 2, diff: 'EASY', r: 'Good knowledge.', w: 'Cholera is waterborne.' },
        { q: 'Which vitamin prevents night blindness?', op: ['A', 'B', 'C', 'D'], ans: 1, diff: 'EASY', r: 'Correct.', w: 'Vitamin A for night vision.' },
        { q: 'Rickets caused by deficiency of:', op: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'], ans: 4, diff: 'EASY', r: 'Good recall.', w: 'Vitamin D deficiency → rickets.' },
        { q: 'White blood cells help in:', op: ['Digestion', 'Immunity', 'Breathing', 'Movement'], ans: 2, diff: 'MEDIUM', r: 'Good understanding.', w: 'WBCs fight infections.' },
        { q: 'Typhoid is caused by:', op: ['Virus', 'Fungi', 'Bacteria', 'Protozoa'], ans: 3, diff: 'MEDIUM', r: 'Accurate.', w: 'Salmonella typhi bacteria.' },
        { q: 'Vaccination provides:', op: ['Natural immunity', 'Artificial immunity', 'No immunity', 'Weakness'], ans: 2, diff: 'MEDIUM', r: 'Good concept.', w: 'Vaccines provide artificial immunity.' },
        { q: 'Goitre caused by deficiency of:', op: ['Iron', 'Iodine', 'Calcium', 'Zinc'], ans: 2, diff: 'HARD', r: 'Excellent recall.', w: 'Iodine deficiency → goitre.' },
        { q: 'Vector for dengue:', op: ['Anopheles', 'Aedes', 'Housefly', 'Cockroach'], ans: 2, diff: 'HARD', r: 'Strong knowledge.', w: 'Aedes mosquito spreads dengue.' },
    ],
    Intermediate: [
        { q: 'Pathogen means:', op: ['Medicine', 'Disease-causing organism', 'Food', 'Vitamin'], ans: 2, diff: 'EASY', r: 'Good vocabulary.', w: 'Pathogen = disease-causing agent.' },
        { q: 'Which is a viral disease?', op: ['TB', 'Cholera', 'Common cold', 'Typhoid'], ans: 3, diff: 'EASY', r: 'Accurate.', w: 'Common cold is viral.' },
        { q: 'Balanced diet contains:', op: ['Only carbs', 'Only protein', 'All nutrients', 'Only vitamins'], ans: 3, diff: 'EASY', r: 'Good nutrition concept.', w: 'Balanced diet has all nutrients.' },
        { q: 'Immunity means:', op: ['Disease', 'Resistance to disease', 'Food', 'Exercise'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Immunity = resistance to disease.' },
        { q: 'Personal hygiene prevents:', op: ['Growth', 'Disease', 'Movement', 'Sleep'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Hygiene prevents disease.' },
        { q: 'Antibodies are produced by:', op: ['RBC', 'WBC', 'Platelets', 'Plasma'], ans: 2, diff: 'MEDIUM', r: 'Excellent.', w: 'White blood cells produce antibodies.' },
        { q: 'Pasteurization kills germs in:', op: ['Soil', 'Water', 'Milk', 'Air'], ans: 3, diff: 'MEDIUM', r: 'Good knowledge.', w: 'Pasteurization treats milk.' },
        { q: 'ORS is used for:', op: ['Headache', 'Dehydration', 'Fracture', 'Fever'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'ORS treats dehydration.' },
        { q: 'Ringworm is caused by:', op: ['Worm', 'Fungi', 'Bacteria', 'Virus'], ans: 2, diff: 'HARD', r: 'Excellent — tricky name!', w: 'Ringworm is actually a fungal infection.' },
        { q: 'Penicillin is obtained from:', op: ['Bacteria', 'Fungi', 'Virus', 'Algae'], ans: 2, diff: 'HARD', r: 'Strong history knowledge.', w: 'Penicillin comes from Penicillium fungus.' },
    ],
    Advance: [
        { q: 'BCG vaccine protects against:', op: ['Polio', 'Tuberculosis', 'Malaria', 'Dengue'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'BCG for tuberculosis.' },
        { q: 'Kwashiorkor caused by deficiency of:', op: ['Carbohydrates', 'Protein', 'Fats', 'Vitamins'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Protein deficiency → kwashiorkor.' },
        { q: 'Contaminated food causes:', op: ['Healthy growth', 'Food poisoning', 'Strength', 'Nothing'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Contaminated food causes food poisoning.' },
        { q: 'Hereditary diseases are:', op: ['Communicable', 'Non-communicable', 'Viral', 'Bacterial'], ans: 2, diff: 'EASY', r: 'Good classification.', w: 'Hereditary = non-communicable.' },
        { q: 'Antibiotics should be used:', op: ['Daily', 'As prescribed', 'Anytime', 'Never'], ans: 2, diff: 'EASY', r: 'Excellent awareness.', w: 'Only as prescribed by doctor.' },
        { q: 'HIV attacks which cells?', op: ['RBC', 'WBC (T-cells)', 'Platelets', 'Nerve cells'], ans: 2, diff: 'MEDIUM', r: 'Strong knowledge.', w: 'HIV attacks T-helper cells (WBC).' },
        { q: 'Marasmus caused by deficiency of:', op: ['Protein & calories', 'Only vitamins', 'Only iron', 'Only water'], ans: 1, diff: 'MEDIUM', r: 'Good understanding.', w: 'Protein-calorie malnutrition → marasmus.' },
        { q: 'Rabies spread by:', op: ['Water', 'Dog bite', 'Touch', 'Air'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Rabies spreads through animal bites.' },
        { q: 'Antibiotic resistance occurs when:', op: ['Body gets stronger', 'Bacteria become resistant', 'Virus dies', 'Nothing'], ans: 2, diff: 'HARD', r: 'Excellent concept.', w: 'Overuse leads to resistant bacteria.' },
        { q: 'Polio vaccine developed by:', op: ['Jenner', 'Jonas Salk', 'Pasteur', 'Fleming'], ans: 2, diff: 'HARD', r: 'Great history recall.', w: 'Jonas Salk developed polio vaccine.' },
    ],
    Challenge: [
        { q: 'WHO stands for:', op: ['World Health Organization', 'World Human Organization', 'World Hospital Organization', 'World Help Organization'], ans: 1, diff: 'EASY', r: 'Good recall.', w: 'World Health Organization.' },
        { q: 'Infectious disease means:', op: ['Hereditary', 'Communicable', 'Nutritional', 'Mental'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Infectious = communicable.' },
        { q: 'Clean water prevents:', op: ['All diseases', 'Waterborne diseases', 'Genetic diseases', 'Mental illness'], ans: 2, diff: 'EASY', r: 'Good.', w: 'Clean water prevents waterborne diseases.' },
        { q: 'Protein-rich food:', op: ['Rice', 'Pulses/dal', 'Sugar', 'Oil'], ans: 2, diff: 'EASY', r: 'Good nutrition.', w: 'Pulses/dal are protein-rich.' },
        { q: 'Mosquito nets prevent:', op: ['Cold', 'Mosquito-borne diseases', 'Headache', 'Fracture'], ans: 2, diff: 'EASY', r: 'Practical knowledge.', w: 'Nets prevent mosquito-borne diseases.' },
        { q: 'Epidemic means:', op: ['One person ill', 'Disease spreading widely', 'No disease', 'Cure found'], ans: 2, diff: 'MEDIUM', r: 'Excellent vocabulary.', w: 'Epidemic = widespread disease.' },
        { q: 'Active immunity develops after:', op: ['Sleeping', 'Infection or vaccination', 'Eating', 'Drinking water'], ans: 2, diff: 'MEDIUM', r: 'Strong concept.', w: 'Infection/vaccine → active immunity.' },
        { q: 'Carrier of disease:', op: ['Medicine', 'Vector', 'Food only', 'None'], ans: 2, diff: 'MEDIUM', r: 'Good.', w: 'Vectors carry disease organisms.' },
        { q: 'Autoimmune disease means:', op: ['Body attacks itself', 'External infection', 'Nutritional', 'Genetic only'], ans: 1, diff: 'HARD', r: 'Excellent advanced concept.', w: 'Immune system attacks own body.' },
        { q: 'Pandemic means:', op: ['Local disease', 'Worldwide disease spread', 'Seasonal allergy', 'One case'], ans: 2, diff: 'HARD', r: 'Strong vocabulary.', w: 'Pandemic = global disease spread.' },
    ],
};

// ========== CHAPTER 3: Force and Pressure ==========
const ch3: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Force is a:', op: ['Push or pull', 'Colour', 'Sound', 'Smell'], ans: 1, diff: 'EASY', r: 'Good basic concept.', w: 'Force = push or pull.' },
        { q: 'SI unit of force is:', op: ['Meter', 'Newton', 'Kilogram', 'Second'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Force measured in Newtons.' },
        { q: 'Pressure = Force ÷:', op: ['Mass', 'Area', 'Volume', 'Time'], ans: 2, diff: 'EASY', r: 'Correct formula.', w: 'Pressure = Force/Area.' },
        { q: 'Gravitational force pulls objects:', op: ['Upward', 'Downward', 'Sideways', 'Nowhere'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Gravity pulls downward.' },
        { q: 'Friction opposes:', op: ['Gravity', 'Motion', 'Light', 'Sound'], ans: 2, diff: 'EASY', r: 'Excellent.', w: 'Friction opposes motion.' },
        { q: 'Unit of pressure is:', op: ['Newton', 'Pascal', 'Meter', 'Kilogram'], ans: 2, diff: 'MEDIUM', r: 'Good recall.', w: 'Pressure measured in Pascal (Pa).' },
        { q: 'Atmospheric pressure acts in:', op: ['One direction', 'All directions', 'Only downward', 'Only upward'], ans: 2, diff: 'MEDIUM', r: 'Strong concept.', w: 'Atmospheric pressure acts in all directions.' },
        { q: 'Liquid pressure increases with:', op: ['Colour', 'Depth', 'Width', 'Temperature only'], ans: 2, diff: 'MEDIUM', r: 'Good understanding.', w: 'Deeper = more pressure.' },
        { q: 'Sharp knife cuts better because:', op: ['More area', 'Less area = more pressure', 'More force', 'Less force'], ans: 2, diff: 'HARD', r: 'Excellent pressure application.', w: 'Less area → more pressure.' },
        { q: 'Force can change an object\'s:', op: ['Colour', 'Shape, speed, direction', 'Smell', 'Taste'], ans: 2, diff: 'HARD', r: 'Strong understanding.', w: 'Force changes shape, speed, or direction.' },
    ],
    Beginner: [
        { q: 'Muscular force is exerted by:', op: ['Machines', 'Muscles', 'Magnets', 'Gravity'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'Muscles exert muscular force.' },
        { q: 'Contact force requires:', op: ['No contact', 'Physical contact', 'Light', 'Sound'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Contact force needs physical touch.' },
        { q: 'Magnetic force is:', op: ['Contact force', 'Non-contact force', 'No force', 'Friction'], ans: 2, diff: 'EASY', r: 'Good classification.', w: 'Magnetic force is non-contact.' },
        { q: 'Weight of object on moon is:', op: ['Same as earth', 'Less than earth', 'More than earth', 'Zero'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Moon has less gravity → less weight.' },
        { q: 'Electrostatic force is:', op: ['Contact', 'Non-contact', 'Friction', 'Muscular'], ans: 2, diff: 'EASY', r: 'Good classification.', w: 'Electrostatic force is non-contact.' },
        { q: 'Wider tyre on truck because:', op: ['Looks better', 'Distributes pressure', 'Increases pressure', 'No reason'], ans: 2, diff: 'MEDIUM', r: 'Good application.', w: 'More area = less pressure on road.' },
        { q: 'Camel walks easily on sand due to:', op: ['Light weight', 'Wide feet', 'Thin legs', 'Long neck'], ans: 2, diff: 'MEDIUM', r: 'Excellent real-world concept.', w: 'Wide feet = less pressure on sand.' },
        { q: 'Spring balance measures:', op: ['Mass', 'Force', 'Length', 'Volume'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Spring balance measures force.' },
        { q: 'Net force on stationary object:', op: ['Maximum', 'Minimum', 'Zero', 'Infinite'], ans: 3, diff: 'HARD', r: 'Strong Newton\'s law.', w: 'Balanced forces → net force = zero.' },
        { q: 'Pascal\'s law applies to:', op: ['Solids', 'Liquids', 'Gases only', 'Both liquids and gases'], ans: 4, diff: 'HARD', r: 'Excellent advanced concept.', w: 'Pascal\'s law applies to fluids (liquids & gases).' },
    ],
    Intermediate: [
        { q: 'Gravity is discovered by:', op: ['Einstein', 'Newton', 'Galileo', 'Edison'], ans: 2, diff: 'EASY', r: 'Good history.', w: 'Newton discovered gravity.' },
        { q: '1 Pascal equals:', op: ['1 N/m', '1 N/m²', '1 kg/m', '1 m/s²'], ans: 2, diff: 'EASY', r: 'Accurate unit.', w: '1 Pa = 1 N/m².' },
        { q: 'Friction is useful for:', op: ['Walking', 'Sliding', 'Both', 'Neither'], ans: 1, diff: 'EASY', r: 'Good understanding.', w: 'Friction helps us walk.' },
        { q: 'Pressure increases when area:', op: ['Increases', 'Decreases', 'Stays same', 'Doubles'], ans: 2, diff: 'EASY', r: 'Correct relationship.', w: 'Less area = more pressure.' },
        { q: 'Force is a vector because it has:', op: ['Only magnitude', 'Magnitude and direction', 'Only direction', 'Neither'], ans: 2, diff: 'EASY', r: 'Good physics concept.', w: 'Vectors have magnitude + direction.' },
        { q: 'If force = 100N, area = 5m², pressure =:', op: ['20 Pa', '500 Pa', '50 Pa', '105 Pa'], ans: 1, diff: 'MEDIUM', r: 'Good calculation.', w: '100/5 = 20 Pa.' },
        { q: 'Hydraulic machines work on:', op: ['Newton\'s law', 'Pascal\'s law', 'Ohm\'s law', 'Boyle\'s law'], ans: 2, diff: 'MEDIUM', r: 'Excellent.', w: 'Hydraulic machines use Pascal\'s law.' },
        { q: 'Buoyant force acts:', op: ['Downward', 'Upward', 'Sideways', 'No direction'], ans: 2, diff: 'MEDIUM', r: 'Strong concept.', w: 'Buoyancy acts upward.' },
        { q: 'If force doubles and area stays same, pressure:', op: ['Halves', 'Doubles', 'Stays same', 'Triples'], ans: 2, diff: 'HARD', r: 'Excellent proportional reasoning.', w: 'P = F/A, F doubles → P doubles.' },
        { q: 'Atmospheric pressure at sea level:', op: ['Zero', '1 atm', '2 atm', '0.5 atm'], ans: 2, diff: 'HARD', r: 'Good scientific knowledge.', w: '1 atmosphere at sea level.' },
    ],
    Advance: [
        { q: 'Streamlined shapes reduce:', op: ['Weight', 'Friction/drag', 'Gravity', 'Pressure'], ans: 2, diff: 'EASY', r: 'Good application.', w: 'Streamline shapes reduce drag.' },
        { q: 'Rolling friction is ___ sliding friction:', op: ['Greater than', 'Less than', 'Equal to', 'Unrelated to'], ans: 2, diff: 'EASY', r: 'Accurate comparison.', w: 'Rolling friction < sliding friction.' },
        { q: 'Lubricants:', op: ['Increase friction', 'Reduce friction', 'Have no effect', 'Increase weight'], ans: 2, diff: 'EASY', r: 'Good practical knowledge.', w: 'Lubricants reduce friction.' },
        { q: 'Dam walls are thicker at bottom because:', op: ['Looks better', 'More water pressure at bottom', 'Less water', 'No reason'], ans: 2, diff: 'EASY', r: 'Excellent real-world connection.', w: 'Water pressure increases with depth.' },
        { q: 'Acceleration due to gravity (g):', op: ['9.8 m/s²', '10 m', '98 m/s', '1 m/s²'], ans: 1, diff: 'EASY', r: 'Good recall.', w: 'g ≈ 9.8 m/s².' },
        { q: 'If area halves, pressure:', op: ['Halves', 'Doubles', 'Stays same', 'Triples'], ans: 2, diff: 'MEDIUM', r: 'Good inverse relationship.', w: 'Half area → double pressure.' },
        { q: 'Heavy schoolbag straps are wide to:', op: ['Look better', 'Reduce pressure on shoulders', 'Increase pressure', 'No reason'], ans: 2, diff: 'MEDIUM', r: 'Excellent practical application.', w: 'Wide straps = less pressure.' },
        { q: 'Torricelli invented:', op: ['Telescope', 'Barometer', 'Thermometer', 'Compass'], ans: 2, diff: 'MEDIUM', r: 'Good history.', w: 'Torricelli invented the barometer.' },
        { q: 'Force of 200N on 0.01m² gives pressure:', op: ['2000 Pa', '20000 Pa', '200 Pa', '20 Pa'], ans: 2, diff: 'HARD', r: 'Excellent calculation.', w: '200/0.01 = 20000 Pa.' },
        { q: 'Archimedes principle relates to:', op: ['Friction', 'Buoyancy', 'Magnetism', 'Electricity'], ans: 2, diff: 'HARD', r: 'Strong knowledge.', w: 'Archimedes principle = buoyancy.' },
    ],
    Challenge: [
        { q: 'Nail has pointed tip to:', op: ['Look sharp', 'Increase pressure', 'Decrease pressure', 'Save material'], ans: 2, diff: 'EASY', r: 'Good application.', w: 'Small area → more pressure.' },
        { q: 'Tractor has wide tyres to:', op: ['Go faster', 'Reduce pressure on soil', 'Look bigger', 'Carry more'], ans: 2, diff: 'EASY', r: 'Correct reasoning.', w: 'Wide tyres distribute pressure.' },
        { q: 'Suction cups work due to:', op: ['Gravity', 'Atmospheric pressure', 'Friction', 'Magnetism'], ans: 2, diff: 'EASY', r: 'Excellent.', w: 'Suction cups use atmospheric pressure.' },
        { q: 'In space, atmospheric pressure is:', op: ['Very high', 'Normal', 'Zero/negligible', 'Double'], ans: 3, diff: 'EASY', r: 'Good understanding.', w: 'No atmosphere in space → no pressure.' },
        { q: 'Weight = mass ×:', op: ['Speed', 'g (gravity)', 'Area', 'Volume'], ans: 2, diff: 'EASY', r: 'Correct formula.', w: 'W = m × g.' },
        { q: 'If same force on area 10m² vs 5m², which has more pressure?', op: ['10m²', '5m²', 'Same', 'Cannot tell'], ans: 2, diff: 'MEDIUM', r: 'Good reasoning.', w: 'Smaller area = more pressure.' },
        { q: 'Blood pressure is measured by:', op: ['Thermometer', 'Sphygmomanometer', 'Barometer', 'Scale'], ans: 2, diff: 'MEDIUM', r: 'Excellent vocabulary.', w: 'Sphygmomanometer measures blood pressure.' },
        { q: 'Friction produces:', op: ['Cold', 'Heat', 'Light only', 'Nothing'], ans: 2, diff: 'MEDIUM', r: 'Good concept.', w: 'Friction generates heat.' },
        { q: 'If F=50N, A=0.005m², P=:', op: ['10000 Pa', '250 Pa', '100 Pa', '1000 Pa'], ans: 1, diff: 'HARD', r: 'Excellent calculation.', w: '50/0.005 = 10000 Pa.' },
        { q: 'Manometer measures:', op: ['Temperature', 'Gas pressure', 'Speed', 'Weight'], ans: 2, diff: 'HARD', r: 'Strong instrument knowledge.', w: 'Manometer measures gas pressure.' },
    ],
};

// ========== CHAPTER 4: Current Electricity and Magnetism ==========
const ch4: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Electric current is flow of:', op: ['Protons', 'Electrons', 'Neutrons', 'Atoms'], ans: 2, diff: 'EASY', r: 'Correct!', w: 'Current = flow of electrons.' },
        { q: 'SI unit of current is:', op: ['Volt', 'Ampere', 'Ohm', 'Watt'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'Current measured in Ampere.' },
        { q: 'Battery provides:', op: ['AC', 'DC', 'Both', 'None'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Battery provides direct current.' },
        { q: 'Unit of resistance is:', op: ['Volt', 'Ampere', 'Ohm', 'Watt'], ans: 3, diff: 'EASY', r: 'Good knowledge.', w: 'Resistance in Ohm (Ω).' },
        { q: 'Magnet attracts:', op: ['Wood', 'Plastic', 'Iron', 'Glass'], ans: 3, diff: 'EASY', r: 'Excellent.', w: 'Magnets attract iron.' },
        { q: 'Ohm\'s law: V =', op: ['I × R', 'I / R', 'I + R', 'I − R'], ans: 1, diff: 'MEDIUM', r: 'Good formula recall.', w: 'V = I × R.' },
        { q: 'Good conductor of electricity:', op: ['Rubber', 'Wood', 'Copper', 'Plastic'], ans: 3, diff: 'MEDIUM', r: 'Accurate identification.', w: 'Copper is a good conductor.' },
        { q: 'Electromagnet works on:', op: ['Gravity', 'Current through coil', 'Light', 'Sound'], ans: 2, diff: 'MEDIUM', r: 'Strong concept.', w: 'Current in coil creates magnetic field.' },
        { q: 'LED stands for:', op: ['Light Emitting Diode', 'Low Energy Device', 'Light Electric Device', 'Large Electron Diode'], ans: 1, diff: 'HARD', r: 'Excellent.', w: 'Light Emitting Diode.' },
        { q: 'Fuse wire protects circuit from:', op: ['Low voltage', 'Overloading', 'Underloading', 'Magnetism'], ans: 2, diff: 'HARD', r: 'Strong safety knowledge.', w: 'Fuse melts during overload.' },
    ],
    Beginner: [
        { q: 'Switch is used to:', op: ['Increase current', 'Break/make circuit', 'Store charge', 'Create voltage'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Switch makes or breaks circuit.' },
        { q: 'Insulator example:', op: ['Copper', 'Iron', 'Rubber', 'Aluminium'], ans: 3, diff: 'EASY', r: 'Accurate.', w: 'Rubber is an insulator.' },
        { q: 'Electric cell has:', op: ['1 terminal', '2 terminals', '3 terminals', 'No terminal'], ans: 2, diff: 'EASY', r: 'Good recall.', w: 'Cell has positive and negative terminals.' },
        { q: 'Unit of voltage is:', op: ['Ampere', 'Volt', 'Ohm', 'Watt'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Voltage in Volts.' },
        { q: 'Like poles of magnets:', op: ['Attract', 'Repel', 'No effect', 'Combine'], ans: 2, diff: 'EASY', r: 'Good magnet concept.', w: 'Like poles repel.' },
        { q: 'Series circuit has:', op: ['Multiple paths', 'Single path', 'No path', 'Branching paths'], ans: 2, diff: 'MEDIUM', r: 'Good understanding.', w: 'Series = single path.' },
        { q: 'Parallel circuit has:', op: ['Single path', 'Multiple paths', 'No connection', 'Broken wire'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Parallel = multiple paths.' },
        { q: 'Magnetic field lines go from:', op: ['South to North outside', 'North to South outside', 'Random', 'No direction'], ans: 2, diff: 'MEDIUM', r: 'Good field line concept.', w: 'N to S outside the magnet.' },
        { q: 'If R increases, current:', op: ['Increases', 'Decreases', 'Stays same', 'Doubles'], ans: 2, diff: 'HARD', r: 'Excellent Ohm\'s law.', w: 'More resistance → less current.' },
        { q: 'Electric motor converts:', op: ['Light to sound', 'Electrical to mechanical', 'Heat to light', 'Mechanical to electrical'], ans: 2, diff: 'HARD', r: 'Strong understanding.', w: 'Motor: electrical → mechanical energy.' },
    ],
    Intermediate: [
        { q: 'Ammeter measures:', op: ['Voltage', 'Current', 'Resistance', 'Power'], ans: 2, diff: 'EASY', r: 'Good instrument knowledge.', w: 'Ammeter measures current.' },
        { q: 'Voltmeter measures:', op: ['Current', 'Voltage', 'Resistance', 'Speed'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Voltmeter measures voltage.' },
        { q: 'Earth is a:', op: ['Small magnet', 'Giant magnet', 'Non-magnet', 'Electric field'], ans: 2, diff: 'EASY', r: 'Good concept.', w: 'Earth behaves as a giant magnet.' },
        { q: 'Compass needle points:', op: ['East-West', 'North-South', 'Up-Down', 'Random'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Compass aligns N-S.' },
        { q: 'Bulb glows when circuit is:', op: ['Open', 'Closed', 'Broken', 'Off'], ans: 2, diff: 'EASY', r: 'Good understanding.', w: 'Closed circuit allows current.' },
        { q: 'If V=12V and R=4Ω, I=:', op: ['3A', '48A', '8A', '16A'], ans: 1, diff: 'MEDIUM', r: 'Good calculation.', w: 'I = V/R = 12/4 = 3A.' },
        { q: 'Electromagnet is temporary because:', op: ['It breaks', 'Magnetism stops when current stops', 'It melts', 'It is weak'], ans: 2, diff: 'MEDIUM', r: 'Excellent concept.', w: 'No current → no magnetism.' },
        { q: 'Ammeter is connected in:', op: ['Parallel', 'Series', 'Either', 'Neither'], ans: 2, diff: 'MEDIUM', r: 'Strong circuit knowledge.', w: 'Ammeter connected in series.' },
        { q: 'If V=220V, I=5A, R=:', op: ['44Ω', '1100Ω', '225Ω', '215Ω'], ans: 1, diff: 'HARD', r: 'Excellent calculation.', w: 'R = V/I = 220/5 = 44Ω.' },
        { q: 'Generator converts:', op: ['Electrical to mechanical', 'Mechanical to electrical', 'Heat to light', 'Sound to light'], ans: 2, diff: 'HARD', r: 'Strong energy conversion.', w: 'Generator: mechanical → electrical.' },
    ],
    Advance: [
        { q: 'Heating element made of:', op: ['Copper', 'Nichrome', 'Aluminium', 'Gold'], ans: 2, diff: 'EASY', r: 'Good knowledge.', w: 'Nichrome has high resistance → heating.' },
        { q: 'Electric power unit is:', op: ['Ampere', 'Volt', 'Watt', 'Ohm'], ans: 3, diff: 'EASY', r: 'Accurate.', w: 'Power measured in Watts.' },
        { q: 'P = V ×:', op: ['R', 'I', 'Ω', 'W'], ans: 2, diff: 'EASY', r: 'Good formula.', w: 'P = V × I.' },
        { q: 'Electromagnets used in:', op: ['Cranes', 'Cooking', 'Washing', 'Walking'], ans: 1, diff: 'EASY', r: 'Good application.', w: 'Cranes use electromagnets.' },
        { q: 'Magnetic compass invented in:', op: ['India', 'China', 'USA', 'Russia'], ans: 2, diff: 'EASY', r: 'Good history.', w: 'Chinese invented compass.' },
        { q: 'If V=10V, I=2A, P=:', op: ['5W', '20W', '12W', '8W'], ans: 2, diff: 'MEDIUM', r: 'Excellent calculation.', w: 'P = 10 × 2 = 20W.' },
        { q: 'Voltmeter is connected in:', op: ['Series', 'Parallel', 'Either', 'Neither'], ans: 2, diff: 'MEDIUM', r: 'Strong knowledge.', w: 'Voltmeter connected in parallel.' },
        { q: 'MCB replaced:', op: ['Switch', 'Fuse', 'Battery', 'Wire'], ans: 2, diff: 'MEDIUM', r: 'Good practical knowledge.', w: 'MCB (Miniature Circuit Breaker) replaces fuse.' },
        { q: 'Resistance in series: R_total =', op: ['R1+R2', 'R1×R2', 'R1/R2', 'R1−R2'], ans: 1, diff: 'HARD', r: 'Excellent series formula.', w: 'Series: R_total = R1 + R2.' },
        { q: 'Electric energy: E =', op: ['P × t', 'P / t', 'P + t', 'P − t'], ans: 1, diff: 'HARD', r: 'Outstanding formula knowledge.', w: 'Energy = Power × time.' },
    ],
    Challenge: [
        { q: 'Electric bell uses:', op: ['Permanent magnet', 'Electromagnet', 'No magnet', 'Light'], ans: 2, diff: 'EASY', r: 'Good application.', w: 'Electric bell uses electromagnet.' },
        { q: 'Short circuit occurs when:', op: ['Wires touch directly', 'Switch is off', 'Battery is removed', 'Circuit is open'], ans: 1, diff: 'EASY', r: 'Accurate.', w: 'Short circuit = direct wire contact.' },
        { q: '1 kWh equals:', op: ['1000 Wh', '100 Wh', '10 Wh', '1 Wh'], ans: 1, diff: 'EASY', r: 'Good unit conversion.', w: '1 kWh = 1000 Watt-hours.' },
        { q: 'Earthing protects from:', op: ['Theft', 'Electric shock', 'Rain', 'Cold'], ans: 2, diff: 'EASY', r: 'Good safety knowledge.', w: 'Earthing prevents electric shock.' },
        { q: 'Magnetic field strongest at:', op: ['Centre', 'Poles', 'Middle of sides', 'Far away'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Strongest at poles.' },
        { q: 'If 3 resistors of 6Ω each in series, total R:', op: ['2Ω', '6Ω', '18Ω', '12Ω'], ans: 3, diff: 'MEDIUM', r: 'Excellent series calculation.', w: '6+6+6 = 18Ω.' },
        { q: 'Domestic supply in India is:', op: ['110V AC', '220V AC', '12V DC', '440V DC'], ans: 2, diff: 'MEDIUM', r: 'Good practical knowledge.', w: 'India uses 220V AC.' },
        { q: 'Solenoid behaves like:', op: ['Bulb', 'Bar magnet', 'Resistor', 'Battery'], ans: 2, diff: 'MEDIUM', r: 'Strong electromagnet concept.', w: 'Current-carrying solenoid = bar magnet.' },
        { q: 'If P=100W, t=5hours, energy=:', op: ['500Wh', '20Wh', '105Wh', '95Wh'], ans: 1, diff: 'HARD', r: 'Excellent energy calculation.', w: 'E = 100×5 = 500 Wh.' },
        { q: 'Fleming\'s left hand rule gives direction of:', op: ['Current', 'Force on conductor', 'Voltage', 'Resistance'], ans: 2, diff: 'HARD', r: 'Outstanding physics knowledge.', w: 'Left hand rule → force direction on conductor.' },
    ],
};

// ========== CHAPTER 5: Inside the Atom ==========
const ch5: Record<string, QuestionData[]> = {
    Diagnostic: [
        { q: 'Atom is the smallest unit of:', op: ['Compound', 'Element', 'Mixture', 'Solution'], ans: 2, diff: 'EASY', r: 'Good basic concept.', w: 'Atom is smallest unit of element.' },
        { q: 'Electron has charge:', op: ['Positive', 'Negative', 'Neutral', 'No charge'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Electron has negative charge.' },
        { q: 'Proton has charge:', op: ['Positive', 'Negative', 'Neutral', 'No charge'], ans: 1, diff: 'EASY', r: 'Correct.', w: 'Proton has positive charge.' },
        { q: 'Neutron has charge:', op: ['Positive', 'Negative', 'Neutral', 'Double positive'], ans: 3, diff: 'EASY', r: 'Good recall.', w: 'Neutron is electrically neutral.' },
        { q: 'Nucleus contains:', op: ['Electrons only', 'Protons and neutrons', 'Only neutrons', 'Only protons'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Nucleus has protons + neutrons.' },
        { q: 'Electrons revolve around:', op: ['Proton', 'Neutron', 'Nucleus', 'Other electrons'], ans: 3, diff: 'MEDIUM', r: 'Strong concept.', w: 'Electrons orbit the nucleus.' },
        { q: 'Atomic number equals number of:', op: ['Neutrons', 'Protons', 'Electrons in outer shell', 'Mass'], ans: 2, diff: 'MEDIUM', r: 'Excellent.', w: 'Atomic number = number of protons.' },
        { q: 'Mass number = protons +:', op: ['Electrons', 'Neutrons', 'Photons', 'Atoms'], ans: 2, diff: 'MEDIUM', r: 'Good formula.', w: 'Mass number = protons + neutrons.' },
        { q: 'Who discovered electron?', op: ['Rutherford', 'Thomson', 'Bohr', 'Dalton'], ans: 2, diff: 'HARD', r: 'Excellent history.', w: 'J.J. Thomson discovered electron.' },
        { q: 'Who discovered nucleus?', op: ['Thomson', 'Rutherford', 'Bohr', 'Chadwick'], ans: 2, diff: 'HARD', r: 'Strong history recall.', w: 'Rutherford discovered the nucleus.' },
    ],
    Beginner: [
        { q: 'Atom was first proposed by:', op: ['Newton', 'Dalton', 'Thomson', 'Bohr'], ans: 2, diff: 'EASY', r: 'Good history.', w: 'Dalton proposed atomic theory.' },
        { q: 'Electron\'s mass is:', op: ['Very large', 'Very small', 'Equal to proton', 'Zero'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Electron mass is negligible.' },
        { q: 'Proton is found in:', op: ['Orbit', 'Nucleus', 'Outside atom', 'Electron cloud'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Proton is in the nucleus.' },
        { q: 'Most of atom is:', op: ['Solid', 'Empty space', 'Liquid', 'Gas'], ans: 2, diff: 'EASY', r: 'Good concept.', w: 'Atom is mostly empty space.' },
        { q: 'Hydrogen has how many protons?', op: ['0', '1', '2', '3'], ans: 2, diff: 'EASY', r: 'Excellent.', w: 'Hydrogen has 1 proton.' },
        { q: 'Maximum electrons in first shell:', op: ['2', '8', '18', '32'], ans: 1, diff: 'MEDIUM', r: 'Good shell knowledge.', w: 'First shell holds max 2 electrons.' },
        { q: 'Maximum electrons in second shell:', op: ['2', '8', '18', '32'], ans: 2, diff: 'MEDIUM', r: 'Accurate.', w: 'Second shell holds max 8 electrons.' },
        { q: 'Thomson model is called:', op: ['Nuclear model', 'Plum pudding model', 'Planetary model', 'Solar model'], ans: 2, diff: 'MEDIUM', r: 'Good model knowledge.', w: 'Thomson proposed plum pudding model.' },
        { q: 'Isotopes have same:', op: ['Mass number', 'Atomic number', 'Neutrons', 'Weight'], ans: 2, diff: 'HARD', r: 'Excellent.', w: 'Isotopes have same atomic number.' },
        { q: 'Chadwick discovered:', op: ['Electron', 'Proton', 'Neutron', 'Nucleus'], ans: 3, diff: 'HARD', r: 'Strong history.', w: 'Chadwick discovered neutron.' },
    ],
    Intermediate: [
        { q: 'Valence electrons are in:', op: ['Inner shell', 'Outermost shell', 'Nucleus', 'Between shells'], ans: 2, diff: 'EASY', r: 'Good concept.', w: 'Valence electrons are in outermost shell.' },
        { q: 'Carbon atomic number 6 means:', op: ['6 neutrons', '6 protons', '6 shells', '6 molecules'], ans: 2, diff: 'EASY', r: 'Accurate.', w: '6 protons in carbon.' },
        { q: 'Neutral atom has equal:', op: ['Protons and neutrons', 'Protons and electrons', 'Neutrons and electrons', 'Mass and charge'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Neutral atom: protons = electrons.' },
        { q: 'Helium has mass number 4 and atomic number 2. Neutrons:', op: ['2', '4', '6', '0'], ans: 1, diff: 'EASY', r: 'Good calculation.', w: 'Neutrons = 4−2 = 2.' },
        { q: 'Electron shells are also called:', op: ['Layers', 'Orbits/energy levels', 'Rings', 'Circles'], ans: 2, diff: 'EASY', r: 'Good terminology.', w: 'Shells = orbits or energy levels.' },
        { q: 'Sodium (Z=11) electronic configuration:', op: ['2,8,1', '2,8,2', '2,9', '11'], ans: 1, diff: 'MEDIUM', r: 'Excellent configuration.', w: 'Na: 2,8,1.' },
        { q: 'Chlorine (Z=17) valence electrons:', op: ['2', '7', '8', '17'], ans: 2, diff: 'MEDIUM', r: 'Good.', w: 'Cl: 2,8,7 → 7 valence electrons.' },
        { q: 'Bohr\'s model proposed:', op: ['Random electron motion', 'Fixed orbits for electrons', 'No electrons', 'Liquid nucleus'], ans: 2, diff: 'MEDIUM', r: 'Strong model knowledge.', w: 'Bohr said electrons in fixed orbits.' },
        { q: 'Oxygen (Z=8) has electrons in shells:', op: ['2,6', '8', '2,8', '6,2'], ans: 1, diff: 'HARD', r: 'Excellent configuration.', w: 'O: 2,6.' },
        { q: 'Noble gases have ___ valence shell:', op: ['Empty', 'Incomplete', 'Complete/full', 'No shell'], ans: 3, diff: 'HARD', r: 'Outstanding.', w: 'Noble gases have complete valence shells.' },
    ],
    Advance: [
        { q: 'Alpha particles are:', op: ['Electrons', 'Helium nuclei', 'Neutrons', 'Photons'], ans: 2, diff: 'EASY', r: 'Good knowledge.', w: 'Alpha particles = helium nuclei.' },
        { q: 'Rutherford\'s experiment used:', op: ['Electrons', 'Alpha particles', 'Neutrons', 'Light'], ans: 2, diff: 'EASY', r: 'Accurate.', w: 'Gold foil experiment used alpha particles.' },
        { q: 'Most alpha particles passed through gold foil because:', op: ['Gold is weak', 'Atom is mostly empty', 'Gold is magnetic', 'Alpha is small'], ans: 2, diff: 'EASY', r: 'Excellent reasoning.', w: 'Atom is mostly empty space.' },
        { q: 'Ion is formed when atom:', op: ['Gains/loses protons', 'Gains/loses electrons', 'Breaks apart', 'Combines with neutrons'], ans: 2, diff: 'EASY', r: 'Good concept.', w: 'Ion = atom gaining/losing electrons.' },
        { q: 'Cation has:', op: ['Negative charge', 'Positive charge', 'No charge', 'Extra neutrons'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Cation = positive ion.' },
        { q: 'Anion has:', op: ['Positive charge', 'Negative charge', 'No charge', 'Extra protons'], ans: 2, diff: 'MEDIUM', r: 'Good.', w: 'Anion = negative ion.' },
        { q: 'Calcium (Z=20) configuration:', op: ['2,8,10', '2,8,8,2', '2,8,8', '20'], ans: 2, diff: 'MEDIUM', r: 'Excellent.', w: 'Ca: 2,8,8,2.' },
        { q: 'Isotopes of carbon: C-12 and C-14 differ in:', op: ['Protons', 'Electrons', 'Neutrons', 'Atomic number'], ans: 3, diff: 'MEDIUM', r: 'Strong isotope concept.', w: 'Isotopes differ in neutrons.' },
        { q: 'Maximum electrons in third shell:', op: ['2', '8', '18', '32'], ans: 3, diff: 'HARD', r: 'Excellent shell formula.', w: 'Third shell: 2n² = 2(3²) = 18.' },
        { q: 'Electron configuration of Argon (Z=18):', op: ['2,8,8', '2,8,10', '2,8,6,2', '18'], ans: 1, diff: 'HARD', r: 'Outstanding.', w: 'Ar: 2,8,8.' },
    ],
    Challenge: [
        { q: 'Formula for max electrons in shell n:', op: ['n²', '2n²', '2n', 'n³'], ans: 2, diff: 'EASY', r: 'Excellent formula recall.', w: 'Max electrons = 2n².' },
        { q: 'Deuterium has 1 proton and:', op: ['0 neutrons', '1 neutron', '2 neutrons', '3 neutrons'], ans: 2, diff: 'EASY', r: 'Good isotope knowledge.', w: 'Deuterium: 1p + 1n.' },
        { q: 'Electron was discovered using:', op: ['Gold foil', 'Cathode ray tube', 'Microscope', 'Telescope'], ans: 2, diff: 'EASY', r: 'Good history.', w: 'Cathode ray experiment discovered electron.' },
        { q: 'Atom is electrically neutral because:', op: ['No charges', 'Equal protons and electrons', 'Only neutrons', 'Magic'], ans: 2, diff: 'EASY', r: 'Correct.', w: 'Equal p+ and e− → neutral.' },
        { q: 'Nucleus size compared to atom:', op: ['Same', 'Very small', 'Very large', 'Half'], ans: 2, diff: 'EASY', r: 'Excellent.', w: 'Nucleus is very tiny compared to atom.' },
        { q: 'Potassium (Z=19) configuration:', op: ['2,8,9', '2,8,8,1', '2,8,1', '19'], ans: 2, diff: 'MEDIUM', r: 'Excellent configuration.', w: 'K: 2,8,8,1.' },
        { q: 'Fe (Z=26) has protons:', op: ['26', '56', '30', '52'], ans: 1, diff: 'MEDIUM', r: 'Good.', w: 'Z = number of protons = 26.' },
        { q: 'Isobars have same:', op: ['Atomic number', 'Mass number', 'Neutrons', 'Electrons'], ans: 2, diff: 'MEDIUM', r: 'Strong concept.', w: 'Isobars have same mass number.' },
        { q: 'Tritium has 1 proton and:', op: ['0 neutrons', '1 neutron', '2 neutrons', '3 neutrons'], ans: 3, diff: 'HARD', r: 'Excellent isotope knowledge.', w: 'Tritium: 1p + 2n.' },
        { q: 'Gold foil experiment proved atom has:', op: ['No empty space', 'Dense positive nucleus', 'Only electrons', 'No nucleus'], ans: 2, diff: 'HARD', r: 'Outstanding understanding.', w: 'Proved dense positive nucleus exists.' },
    ],
};

export const scienceChaptersData: ChapterData[] = [
    { name: 'Living World and Classification of Microbes', order: 1, levels: makeLevels(ch1), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBaXfRPwWssb8P0DTcUpxPfI&si=n0CNrgDDvQN-OF2R' },
    { name: 'Health and Diseases', order: 2, levels: makeLevels(ch2), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBaXfRPwWssb8P0DTcUpxPfI&si=n0CNrgDDvQN-OF2R' },
    { name: 'Force and Pressure', order: 3, levels: makeLevels(ch3), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBaXfRPwWssb8P0DTcUpxPfI&si=n0CNrgDDvQN-OF2R' },
    { name: 'Current Electricity and Magnetism', order: 4, levels: makeLevels(ch4), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBaXfRPwWssb8P0DTcUpxPfI&si=n0CNrgDDvQN-OF2R' },
    { name: 'Inside the Atom', order: 5, levels: makeLevels(ch5), youtubeLink: 'https://youtube.com/playlist?list=PLjm_mvBNlvBaXfRPwWssb8P0DTcUpxPfI&si=n0CNrgDDvQN-OF2R' },
];

